/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_esp_nimble_hci.h"

static const char* CMockString_esp_nimble_hci_and_controller_deinit = "esp_nimble_hci_and_controller_deinit";
static const char* CMockString_esp_nimble_hci_and_controller_init = "esp_nimble_hci_and_controller_init";
static const char* CMockString_esp_nimble_hci_deinit = "esp_nimble_hci_deinit";
static const char* CMockString_esp_nimble_hci_init = "esp_nimble_hci_init";

typedef struct _CMOCK_esp_nimble_hci_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_esp_nimble_hci_init_CALL_INSTANCE;

typedef struct _CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE;

typedef struct _CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE;

typedef struct _CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE;

static struct mock_esp_nimble_hciInstance
{
  char esp_nimble_hci_init_IgnoreBool;
  esp_err_t esp_nimble_hci_init_FinalReturn;
  char esp_nimble_hci_init_CallbackBool;
  CMOCK_esp_nimble_hci_init_CALLBACK esp_nimble_hci_init_CallbackFunctionPointer;
  int esp_nimble_hci_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_nimble_hci_init_CallInstance;
  char esp_nimble_hci_and_controller_init_IgnoreBool;
  esp_err_t esp_nimble_hci_and_controller_init_FinalReturn;
  char esp_nimble_hci_and_controller_init_CallbackBool;
  CMOCK_esp_nimble_hci_and_controller_init_CALLBACK esp_nimble_hci_and_controller_init_CallbackFunctionPointer;
  int esp_nimble_hci_and_controller_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_nimble_hci_and_controller_init_CallInstance;
  char esp_nimble_hci_deinit_IgnoreBool;
  esp_err_t esp_nimble_hci_deinit_FinalReturn;
  char esp_nimble_hci_deinit_CallbackBool;
  CMOCK_esp_nimble_hci_deinit_CALLBACK esp_nimble_hci_deinit_CallbackFunctionPointer;
  int esp_nimble_hci_deinit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_nimble_hci_deinit_CallInstance;
  char esp_nimble_hci_and_controller_deinit_IgnoreBool;
  esp_err_t esp_nimble_hci_and_controller_deinit_FinalReturn;
  char esp_nimble_hci_and_controller_deinit_CallbackBool;
  CMOCK_esp_nimble_hci_and_controller_deinit_CALLBACK esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer;
  int esp_nimble_hci_and_controller_deinit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_nimble_hci_and_controller_deinit_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_esp_nimble_hci_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.esp_nimble_hci_init_CallInstance;
  if (Mock.esp_nimble_hci_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_nimble_hci_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_nimble_hci_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_nimble_hci_and_controller_init_CallInstance;
  if (Mock.esp_nimble_hci_and_controller_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_nimble_hci_and_controller_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_nimble_hci_deinit_CallInstance;
  if (Mock.esp_nimble_hci_deinit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_nimble_hci_deinit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_nimble_hci_deinit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_nimble_hci_and_controller_deinit_CallInstance;
  if (Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_nimble_hci_and_controller_deinit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_esp_nimble_hci_Init(void)
{
  mock_esp_nimble_hci_Destroy();
}

void mock_esp_nimble_hci_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t esp_nimble_hci_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_nimble_hci_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_nimble_hci_init);
  cmock_call_instance = (CMOCK_esp_nimble_hci_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_nimble_hci_init_CallInstance);
  Mock.esp_nimble_hci_init_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_init_CallInstance);
  if (Mock.esp_nimble_hci_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_nimble_hci_init_FinalReturn;
    memcpy((void*)(&Mock.esp_nimble_hci_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_nimble_hci_init_CallbackBool &&
      Mock.esp_nimble_hci_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_nimble_hci_init_CallbackFunctionPointer(Mock.esp_nimble_hci_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_nimble_hci_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_nimble_hci_init_CallbackFunctionPointer(Mock.esp_nimble_hci_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_nimble_hci_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_init_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_init_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_init_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_nimble_hci_init_IgnoreBool = (char)1;
}

void esp_nimble_hci_init_CMockStopIgnore(void)
{
  if(Mock.esp_nimble_hci_init_IgnoreBool)
    Mock.esp_nimble_hci_init_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_init_CallInstance);
  Mock.esp_nimble_hci_init_IgnoreBool = (char)0;
}

void esp_nimble_hci_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_init_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_init_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_init_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_nimble_hci_init_AddCallback(CMOCK_esp_nimble_hci_init_CALLBACK Callback)
{
  Mock.esp_nimble_hci_init_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_init_CallbackBool = (char)1;
  Mock.esp_nimble_hci_init_CallbackFunctionPointer = Callback;
}

void esp_nimble_hci_init_Stub(CMOCK_esp_nimble_hci_init_CALLBACK Callback)
{
  Mock.esp_nimble_hci_init_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_init_CallbackBool = (char)0;
  Mock.esp_nimble_hci_init_CallbackFunctionPointer = Callback;
}

esp_err_t esp_nimble_hci_and_controller_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_nimble_hci_and_controller_init);
  cmock_call_instance = (CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_nimble_hci_and_controller_init_CallInstance);
  Mock.esp_nimble_hci_and_controller_init_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_and_controller_init_CallInstance);
  if (Mock.esp_nimble_hci_and_controller_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_nimble_hci_and_controller_init_FinalReturn;
    memcpy((void*)(&Mock.esp_nimble_hci_and_controller_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_nimble_hci_and_controller_init_CallbackBool &&
      Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer(Mock.esp_nimble_hci_and_controller_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer(Mock.esp_nimble_hci_and_controller_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_nimble_hci_and_controller_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_and_controller_init_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_and_controller_init_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_and_controller_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_nimble_hci_and_controller_init_IgnoreBool = (char)1;
}

void esp_nimble_hci_and_controller_init_CMockStopIgnore(void)
{
  if(Mock.esp_nimble_hci_and_controller_init_IgnoreBool)
    Mock.esp_nimble_hci_and_controller_init_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_and_controller_init_CallInstance);
  Mock.esp_nimble_hci_and_controller_init_IgnoreBool = (char)0;
}

void esp_nimble_hci_and_controller_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_and_controller_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_and_controller_init_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_and_controller_init_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_and_controller_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_nimble_hci_and_controller_init_AddCallback(CMOCK_esp_nimble_hci_and_controller_init_CALLBACK Callback)
{
  Mock.esp_nimble_hci_and_controller_init_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_and_controller_init_CallbackBool = (char)1;
  Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer = Callback;
}

void esp_nimble_hci_and_controller_init_Stub(CMOCK_esp_nimble_hci_and_controller_init_CALLBACK Callback)
{
  Mock.esp_nimble_hci_and_controller_init_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_and_controller_init_CallbackBool = (char)0;
  Mock.esp_nimble_hci_and_controller_init_CallbackFunctionPointer = Callback;
}

esp_err_t esp_nimble_hci_deinit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_nimble_hci_deinit);
  cmock_call_instance = (CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_nimble_hci_deinit_CallInstance);
  Mock.esp_nimble_hci_deinit_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_deinit_CallInstance);
  if (Mock.esp_nimble_hci_deinit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_nimble_hci_deinit_FinalReturn;
    memcpy((void*)(&Mock.esp_nimble_hci_deinit_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_nimble_hci_deinit_CallbackBool &&
      Mock.esp_nimble_hci_deinit_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_nimble_hci_deinit_CallbackFunctionPointer(Mock.esp_nimble_hci_deinit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_nimble_hci_deinit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_nimble_hci_deinit_CallbackFunctionPointer(Mock.esp_nimble_hci_deinit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_nimble_hci_deinit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_deinit_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_deinit_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_nimble_hci_deinit_IgnoreBool = (char)1;
}

void esp_nimble_hci_deinit_CMockStopIgnore(void)
{
  if(Mock.esp_nimble_hci_deinit_IgnoreBool)
    Mock.esp_nimble_hci_deinit_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_deinit_CallInstance);
  Mock.esp_nimble_hci_deinit_IgnoreBool = (char)0;
}

void esp_nimble_hci_deinit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_deinit_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_deinit_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_nimble_hci_deinit_AddCallback(CMOCK_esp_nimble_hci_deinit_CALLBACK Callback)
{
  Mock.esp_nimble_hci_deinit_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_deinit_CallbackBool = (char)1;
  Mock.esp_nimble_hci_deinit_CallbackFunctionPointer = Callback;
}

void esp_nimble_hci_deinit_Stub(CMOCK_esp_nimble_hci_deinit_CALLBACK Callback)
{
  Mock.esp_nimble_hci_deinit_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_deinit_CallbackBool = (char)0;
  Mock.esp_nimble_hci_deinit_CallbackFunctionPointer = Callback;
}

esp_err_t esp_nimble_hci_and_controller_deinit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_nimble_hci_and_controller_deinit);
  cmock_call_instance = (CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_nimble_hci_and_controller_deinit_CallInstance);
  Mock.esp_nimble_hci_and_controller_deinit_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_and_controller_deinit_CallInstance);
  if (Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_nimble_hci_and_controller_deinit_FinalReturn;
    memcpy((void*)(&Mock.esp_nimble_hci_and_controller_deinit_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_nimble_hci_and_controller_deinit_CallbackBool &&
      Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer(Mock.esp_nimble_hci_and_controller_deinit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer(Mock.esp_nimble_hci_and_controller_deinit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_nimble_hci_and_controller_deinit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_and_controller_deinit_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_and_controller_deinit_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool = (char)1;
}

void esp_nimble_hci_and_controller_deinit_CMockStopIgnore(void)
{
  if(Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool)
    Mock.esp_nimble_hci_and_controller_deinit_CallInstance = CMock_Guts_MemNext(Mock.esp_nimble_hci_and_controller_deinit_CallInstance);
  Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool = (char)0;
}

void esp_nimble_hci_and_controller_deinit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE));
  CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_nimble_hci_and_controller_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_nimble_hci_and_controller_deinit_CallInstance = CMock_Guts_MemChain(Mock.esp_nimble_hci_and_controller_deinit_CallInstance, cmock_guts_index);
  Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_nimble_hci_and_controller_deinit_AddCallback(CMOCK_esp_nimble_hci_and_controller_deinit_CALLBACK Callback)
{
  Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_and_controller_deinit_CallbackBool = (char)1;
  Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer = Callback;
}

void esp_nimble_hci_and_controller_deinit_Stub(CMOCK_esp_nimble_hci_and_controller_deinit_CALLBACK Callback)
{
  Mock.esp_nimble_hci_and_controller_deinit_IgnoreBool = (char)0;
  Mock.esp_nimble_hci_and_controller_deinit_CallbackBool = (char)0;
  Mock.esp_nimble_hci_and_controller_deinit_CallbackFunctionPointer = Callback;
}

