/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_nvs_flash.h"

static const char* CMockString_cfg = "cfg";
static const char* CMockString_nvs_flash_deinit = "nvs_flash_deinit";
static const char* CMockString_nvs_flash_deinit_partition = "nvs_flash_deinit_partition";
static const char* CMockString_nvs_flash_erase = "nvs_flash_erase";
static const char* CMockString_nvs_flash_erase_partition = "nvs_flash_erase_partition";
static const char* CMockString_nvs_flash_erase_partition_ptr = "nvs_flash_erase_partition_ptr";
static const char* CMockString_nvs_flash_generate_keys = "nvs_flash_generate_keys";
static const char* CMockString_nvs_flash_init = "nvs_flash_init";
static const char* CMockString_nvs_flash_init_partition = "nvs_flash_init_partition";
static const char* CMockString_nvs_flash_init_partition_ptr = "nvs_flash_init_partition_ptr";
static const char* CMockString_nvs_flash_read_security_cfg = "nvs_flash_read_security_cfg";
static const char* CMockString_nvs_flash_secure_init = "nvs_flash_secure_init";
static const char* CMockString_nvs_flash_secure_init_partition = "nvs_flash_secure_init_partition";
static const char* CMockString_part_name = "part_name";
static const char* CMockString_partition = "partition";
static const char* CMockString_partition_label = "partition_label";

typedef struct _CMOCK_nvs_flash_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_nvs_flash_init_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_init_partition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const char* Expected_partition_label;
  char IgnoreArg_partition_label;

} CMOCK_nvs_flash_init_partition_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const esp_partition_t* Expected_partition;
  int Expected_partition_Depth;
  char IgnoreArg_partition;

} CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_deinit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_nvs_flash_deinit_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const char* Expected_partition_label;
  char IgnoreArg_partition_label;

} CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_erase_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_nvs_flash_erase_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_erase_partition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const char* Expected_part_name;
  char IgnoreArg_part_name;

} CMOCK_nvs_flash_erase_partition_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const esp_partition_t* Expected_partition;
  int Expected_partition_Depth;
  char IgnoreArg_partition;

} CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_secure_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  nvs_sec_cfg_t* Expected_cfg;
  int Expected_cfg_Depth;
  char ReturnThruPtr_cfg_Used;
  nvs_sec_cfg_t* ReturnThruPtr_cfg_Val;
  size_t ReturnThruPtr_cfg_Size;
  char IgnoreArg_cfg;

} CMOCK_nvs_flash_secure_init_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const char* Expected_partition_label;
  nvs_sec_cfg_t* Expected_cfg;
  int Expected_cfg_Depth;
  char ReturnThruPtr_cfg_Used;
  nvs_sec_cfg_t* ReturnThruPtr_cfg_Val;
  size_t ReturnThruPtr_cfg_Size;
  char IgnoreArg_partition_label;
  char IgnoreArg_cfg;

} CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_generate_keys_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const esp_partition_t* Expected_partition;
  nvs_sec_cfg_t* Expected_cfg;
  int Expected_partition_Depth;
  int Expected_cfg_Depth;
  char ReturnThruPtr_cfg_Used;
  nvs_sec_cfg_t* ReturnThruPtr_cfg_Val;
  size_t ReturnThruPtr_cfg_Size;
  char IgnoreArg_partition;
  char IgnoreArg_cfg;

} CMOCK_nvs_flash_generate_keys_CALL_INSTANCE;

typedef struct _CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const esp_partition_t* Expected_partition;
  nvs_sec_cfg_t* Expected_cfg;
  int Expected_partition_Depth;
  int Expected_cfg_Depth;
  char ReturnThruPtr_cfg_Used;
  nvs_sec_cfg_t* ReturnThruPtr_cfg_Val;
  size_t ReturnThruPtr_cfg_Size;
  char IgnoreArg_partition;
  char IgnoreArg_cfg;

} CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE;

static struct mock_nvs_flashInstance
{
  char nvs_flash_init_IgnoreBool;
  esp_err_t nvs_flash_init_FinalReturn;
  char nvs_flash_init_CallbackBool;
  CMOCK_nvs_flash_init_CALLBACK nvs_flash_init_CallbackFunctionPointer;
  int nvs_flash_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_init_CallInstance;
  char nvs_flash_init_partition_IgnoreBool;
  esp_err_t nvs_flash_init_partition_FinalReturn;
  char nvs_flash_init_partition_CallbackBool;
  CMOCK_nvs_flash_init_partition_CALLBACK nvs_flash_init_partition_CallbackFunctionPointer;
  int nvs_flash_init_partition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_init_partition_CallInstance;
  char nvs_flash_init_partition_ptr_IgnoreBool;
  esp_err_t nvs_flash_init_partition_ptr_FinalReturn;
  char nvs_flash_init_partition_ptr_CallbackBool;
  CMOCK_nvs_flash_init_partition_ptr_CALLBACK nvs_flash_init_partition_ptr_CallbackFunctionPointer;
  int nvs_flash_init_partition_ptr_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_init_partition_ptr_CallInstance;
  char nvs_flash_deinit_IgnoreBool;
  esp_err_t nvs_flash_deinit_FinalReturn;
  char nvs_flash_deinit_CallbackBool;
  CMOCK_nvs_flash_deinit_CALLBACK nvs_flash_deinit_CallbackFunctionPointer;
  int nvs_flash_deinit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_deinit_CallInstance;
  char nvs_flash_deinit_partition_IgnoreBool;
  esp_err_t nvs_flash_deinit_partition_FinalReturn;
  char nvs_flash_deinit_partition_CallbackBool;
  CMOCK_nvs_flash_deinit_partition_CALLBACK nvs_flash_deinit_partition_CallbackFunctionPointer;
  int nvs_flash_deinit_partition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_deinit_partition_CallInstance;
  char nvs_flash_erase_IgnoreBool;
  esp_err_t nvs_flash_erase_FinalReturn;
  char nvs_flash_erase_CallbackBool;
  CMOCK_nvs_flash_erase_CALLBACK nvs_flash_erase_CallbackFunctionPointer;
  int nvs_flash_erase_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_erase_CallInstance;
  char nvs_flash_erase_partition_IgnoreBool;
  esp_err_t nvs_flash_erase_partition_FinalReturn;
  char nvs_flash_erase_partition_CallbackBool;
  CMOCK_nvs_flash_erase_partition_CALLBACK nvs_flash_erase_partition_CallbackFunctionPointer;
  int nvs_flash_erase_partition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_erase_partition_CallInstance;
  char nvs_flash_erase_partition_ptr_IgnoreBool;
  esp_err_t nvs_flash_erase_partition_ptr_FinalReturn;
  char nvs_flash_erase_partition_ptr_CallbackBool;
  CMOCK_nvs_flash_erase_partition_ptr_CALLBACK nvs_flash_erase_partition_ptr_CallbackFunctionPointer;
  int nvs_flash_erase_partition_ptr_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_erase_partition_ptr_CallInstance;
  char nvs_flash_secure_init_IgnoreBool;
  esp_err_t nvs_flash_secure_init_FinalReturn;
  char nvs_flash_secure_init_CallbackBool;
  CMOCK_nvs_flash_secure_init_CALLBACK nvs_flash_secure_init_CallbackFunctionPointer;
  int nvs_flash_secure_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_secure_init_CallInstance;
  char nvs_flash_secure_init_partition_IgnoreBool;
  esp_err_t nvs_flash_secure_init_partition_FinalReturn;
  char nvs_flash_secure_init_partition_CallbackBool;
  CMOCK_nvs_flash_secure_init_partition_CALLBACK nvs_flash_secure_init_partition_CallbackFunctionPointer;
  int nvs_flash_secure_init_partition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_secure_init_partition_CallInstance;
  char nvs_flash_generate_keys_IgnoreBool;
  esp_err_t nvs_flash_generate_keys_FinalReturn;
  char nvs_flash_generate_keys_CallbackBool;
  CMOCK_nvs_flash_generate_keys_CALLBACK nvs_flash_generate_keys_CallbackFunctionPointer;
  int nvs_flash_generate_keys_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_generate_keys_CallInstance;
  char nvs_flash_read_security_cfg_IgnoreBool;
  esp_err_t nvs_flash_read_security_cfg_FinalReturn;
  char nvs_flash_read_security_cfg_CallbackBool;
  CMOCK_nvs_flash_read_security_cfg_CALLBACK nvs_flash_read_security_cfg_CallbackFunctionPointer;
  int nvs_flash_read_security_cfg_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nvs_flash_read_security_cfg_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_nvs_flash_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.nvs_flash_init_CallInstance;
  if (Mock.nvs_flash_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_init_partition_CallInstance;
  if (Mock.nvs_flash_init_partition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_init_partition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_init_partition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_init_partition_ptr_CallInstance;
  if (Mock.nvs_flash_init_partition_ptr_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_init_partition_ptr);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_deinit_CallInstance;
  if (Mock.nvs_flash_deinit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_deinit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_deinit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_deinit_partition_CallInstance;
  if (Mock.nvs_flash_deinit_partition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_deinit_partition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_deinit_partition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_erase_CallInstance;
  if (Mock.nvs_flash_erase_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_erase);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_erase_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_erase_partition_CallInstance;
  if (Mock.nvs_flash_erase_partition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_erase_partition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_erase_partition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_erase_partition_ptr_CallInstance;
  if (Mock.nvs_flash_erase_partition_ptr_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_erase_partition_ptr);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_secure_init_CallInstance;
  if (Mock.nvs_flash_secure_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_secure_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_secure_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_secure_init_partition_CallInstance;
  if (Mock.nvs_flash_secure_init_partition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_secure_init_partition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_generate_keys_CallInstance;
  if (Mock.nvs_flash_generate_keys_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_generate_keys);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_generate_keys_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nvs_flash_read_security_cfg_CallInstance;
  if (Mock.nvs_flash_read_security_cfg_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nvs_flash_read_security_cfg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_nvs_flash_Init(void)
{
  mock_nvs_flash_Destroy();
}

void mock_nvs_flash_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t nvs_flash_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_init);
  cmock_call_instance = (CMOCK_nvs_flash_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_init_CallInstance);
  Mock.nvs_flash_init_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_init_CallInstance);
  if (Mock.nvs_flash_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_init_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_init_CallbackBool &&
      Mock.nvs_flash_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_init_CallbackFunctionPointer(Mock.nvs_flash_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.nvs_flash_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_init_CallbackFunctionPointer(Mock.nvs_flash_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void nvs_flash_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_CALL_INSTANCE));
  CMOCK_nvs_flash_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_init_IgnoreBool = (char)1;
}

void nvs_flash_init_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_init_IgnoreBool)
    Mock.nvs_flash_init_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_init_CallInstance);
  Mock.nvs_flash_init_IgnoreBool = (char)0;
}

void nvs_flash_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_CALL_INSTANCE));
  CMOCK_nvs_flash_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_init_AddCallback(CMOCK_nvs_flash_init_CALLBACK Callback)
{
  Mock.nvs_flash_init_IgnoreBool = (char)0;
  Mock.nvs_flash_init_CallbackBool = (char)1;
  Mock.nvs_flash_init_CallbackFunctionPointer = Callback;
}

void nvs_flash_init_Stub(CMOCK_nvs_flash_init_CALLBACK Callback)
{
  Mock.nvs_flash_init_IgnoreBool = (char)0;
  Mock.nvs_flash_init_CallbackBool = (char)0;
  Mock.nvs_flash_init_CallbackFunctionPointer = Callback;
}

esp_err_t nvs_flash_init_partition(const char* partition_label)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_init_partition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_init_partition);
  cmock_call_instance = (CMOCK_nvs_flash_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_init_partition_CallInstance);
  Mock.nvs_flash_init_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_init_partition_CallInstance);
  if (Mock.nvs_flash_init_partition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_init_partition_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_init_partition_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_init_partition_CallbackBool &&
      Mock.nvs_flash_init_partition_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_init_partition_CallbackFunctionPointer(partition_label, Mock.nvs_flash_init_partition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition_label)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_init_partition,CMockString_partition_label);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_partition_label, partition_label, cmock_line, CMockStringMismatch);
  }
  if (Mock.nvs_flash_init_partition_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_init_partition_CallbackFunctionPointer(partition_label, Mock.nvs_flash_init_partition_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_init_partition(CMOCK_nvs_flash_init_partition_CALL_INSTANCE* cmock_call_instance, const char* partition_label);
void CMockExpectParameters_nvs_flash_init_partition(CMOCK_nvs_flash_init_partition_CALL_INSTANCE* cmock_call_instance, const char* partition_label)
{
  cmock_call_instance->Expected_partition_label = partition_label;
  cmock_call_instance->IgnoreArg_partition_label = 0;
}

void nvs_flash_init_partition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_init_partition_IgnoreBool = (char)1;
}

void nvs_flash_init_partition_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_init_partition_IgnoreBool)
    Mock.nvs_flash_init_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_init_partition_CallInstance);
  Mock.nvs_flash_init_partition_IgnoreBool = (char)0;
}

void nvs_flash_init_partition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* partition_label, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_init_partition(cmock_call_instance, partition_label);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_init_partition_AddCallback(CMOCK_nvs_flash_init_partition_CALLBACK Callback)
{
  Mock.nvs_flash_init_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_init_partition_CallbackBool = (char)1;
  Mock.nvs_flash_init_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_init_partition_Stub(CMOCK_nvs_flash_init_partition_CALLBACK Callback)
{
  Mock.nvs_flash_init_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_init_partition_CallbackBool = (char)0;
  Mock.nvs_flash_init_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_init_partition_CMockIgnoreArg_partition_label(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_init_partition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition_label = 1;
}

esp_err_t nvs_flash_init_partition_ptr(const esp_partition_t* partition)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_init_partition_ptr);
  cmock_call_instance = (CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_init_partition_ptr_CallInstance);
  Mock.nvs_flash_init_partition_ptr_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_init_partition_ptr_CallInstance);
  if (Mock.nvs_flash_init_partition_ptr_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_init_partition_ptr_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_init_partition_ptr_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_init_partition_ptr_CallbackBool &&
      Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer(partition, Mock.nvs_flash_init_partition_ptr_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_init_partition_ptr,CMockString_partition);
    if (cmock_call_instance->Expected_partition == NULL)
      { UNITY_TEST_ASSERT_NULL(partition, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_partition), (void*)(partition), sizeof(const esp_partition_t), cmock_call_instance->Expected_partition_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer(partition, Mock.nvs_flash_init_partition_ptr_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_init_partition_ptr(CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth);
void CMockExpectParameters_nvs_flash_init_partition_ptr(CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth)
{
  cmock_call_instance->Expected_partition = partition;
  cmock_call_instance->Expected_partition_Depth = partition_Depth;
  cmock_call_instance->IgnoreArg_partition = 0;
}

void nvs_flash_init_partition_ptr_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE));
  CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_partition_ptr_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_partition_ptr_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)1;
}

void nvs_flash_init_partition_ptr_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_init_partition_ptr_IgnoreBool)
    Mock.nvs_flash_init_partition_ptr_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_init_partition_ptr_CallInstance);
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)0;
}

void nvs_flash_init_partition_ptr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE));
  CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_partition_ptr_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_partition_ptr_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_init_partition_ptr(cmock_call_instance, partition, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_init_partition_ptr_AddCallback(CMOCK_nvs_flash_init_partition_ptr_CALLBACK Callback)
{
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)0;
  Mock.nvs_flash_init_partition_ptr_CallbackBool = (char)1;
  Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer = Callback;
}

void nvs_flash_init_partition_ptr_Stub(CMOCK_nvs_flash_init_partition_ptr_CALLBACK Callback)
{
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)0;
  Mock.nvs_flash_init_partition_ptr_CallbackBool = (char)0;
  Mock.nvs_flash_init_partition_ptr_CallbackFunctionPointer = Callback;
}

void nvs_flash_init_partition_ptr_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, int partition_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE));
  CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_init_partition_ptr_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_init_partition_ptr_CallInstance, cmock_guts_index);
  Mock.nvs_flash_init_partition_ptr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_init_partition_ptr(cmock_call_instance, partition, partition_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void nvs_flash_init_partition_ptr_CMockIgnoreArg_partition(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_init_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_init_partition_ptr_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition = 1;
}

esp_err_t nvs_flash_deinit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_deinit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_deinit);
  cmock_call_instance = (CMOCK_nvs_flash_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_deinit_CallInstance);
  Mock.nvs_flash_deinit_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_deinit_CallInstance);
  if (Mock.nvs_flash_deinit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_deinit_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_deinit_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_deinit_CallbackBool &&
      Mock.nvs_flash_deinit_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_deinit_CallbackFunctionPointer(Mock.nvs_flash_deinit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.nvs_flash_deinit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_deinit_CallbackFunctionPointer(Mock.nvs_flash_deinit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void nvs_flash_deinit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_deinit_CALL_INSTANCE));
  CMOCK_nvs_flash_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_deinit_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_deinit_CallInstance, cmock_guts_index);
  Mock.nvs_flash_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_deinit_IgnoreBool = (char)1;
}

void nvs_flash_deinit_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_deinit_IgnoreBool)
    Mock.nvs_flash_deinit_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_deinit_CallInstance);
  Mock.nvs_flash_deinit_IgnoreBool = (char)0;
}

void nvs_flash_deinit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_deinit_CALL_INSTANCE));
  CMOCK_nvs_flash_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_deinit_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_deinit_CallInstance, cmock_guts_index);
  Mock.nvs_flash_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_deinit_AddCallback(CMOCK_nvs_flash_deinit_CALLBACK Callback)
{
  Mock.nvs_flash_deinit_IgnoreBool = (char)0;
  Mock.nvs_flash_deinit_CallbackBool = (char)1;
  Mock.nvs_flash_deinit_CallbackFunctionPointer = Callback;
}

void nvs_flash_deinit_Stub(CMOCK_nvs_flash_deinit_CALLBACK Callback)
{
  Mock.nvs_flash_deinit_IgnoreBool = (char)0;
  Mock.nvs_flash_deinit_CallbackBool = (char)0;
  Mock.nvs_flash_deinit_CallbackFunctionPointer = Callback;
}

esp_err_t nvs_flash_deinit_partition(const char* partition_label)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_deinit_partition);
  cmock_call_instance = (CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_deinit_partition_CallInstance);
  Mock.nvs_flash_deinit_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_deinit_partition_CallInstance);
  if (Mock.nvs_flash_deinit_partition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_deinit_partition_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_deinit_partition_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_deinit_partition_CallbackBool &&
      Mock.nvs_flash_deinit_partition_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_deinit_partition_CallbackFunctionPointer(partition_label, Mock.nvs_flash_deinit_partition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition_label)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_deinit_partition,CMockString_partition_label);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_partition_label, partition_label, cmock_line, CMockStringMismatch);
  }
  if (Mock.nvs_flash_deinit_partition_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_deinit_partition_CallbackFunctionPointer(partition_label, Mock.nvs_flash_deinit_partition_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_deinit_partition(CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE* cmock_call_instance, const char* partition_label);
void CMockExpectParameters_nvs_flash_deinit_partition(CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE* cmock_call_instance, const char* partition_label)
{
  cmock_call_instance->Expected_partition_label = partition_label;
  cmock_call_instance->IgnoreArg_partition_label = 0;
}

void nvs_flash_deinit_partition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_deinit_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_deinit_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_deinit_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_deinit_partition_IgnoreBool = (char)1;
}

void nvs_flash_deinit_partition_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_deinit_partition_IgnoreBool)
    Mock.nvs_flash_deinit_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_deinit_partition_CallInstance);
  Mock.nvs_flash_deinit_partition_IgnoreBool = (char)0;
}

void nvs_flash_deinit_partition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* partition_label, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_deinit_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_deinit_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_deinit_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_deinit_partition(cmock_call_instance, partition_label);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_deinit_partition_AddCallback(CMOCK_nvs_flash_deinit_partition_CALLBACK Callback)
{
  Mock.nvs_flash_deinit_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_deinit_partition_CallbackBool = (char)1;
  Mock.nvs_flash_deinit_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_deinit_partition_Stub(CMOCK_nvs_flash_deinit_partition_CALLBACK Callback)
{
  Mock.nvs_flash_deinit_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_deinit_partition_CallbackBool = (char)0;
  Mock.nvs_flash_deinit_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_deinit_partition_CMockIgnoreArg_partition_label(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_deinit_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_deinit_partition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition_label = 1;
}

esp_err_t nvs_flash_erase(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_erase_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_erase);
  cmock_call_instance = (CMOCK_nvs_flash_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_erase_CallInstance);
  Mock.nvs_flash_erase_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_erase_CallInstance);
  if (Mock.nvs_flash_erase_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_erase_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_erase_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_erase_CallbackBool &&
      Mock.nvs_flash_erase_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_erase_CallbackFunctionPointer(Mock.nvs_flash_erase_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.nvs_flash_erase_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_erase_CallbackFunctionPointer(Mock.nvs_flash_erase_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void nvs_flash_erase_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_erase_IgnoreBool = (char)1;
}

void nvs_flash_erase_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_erase_IgnoreBool)
    Mock.nvs_flash_erase_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_erase_CallInstance);
  Mock.nvs_flash_erase_IgnoreBool = (char)0;
}

void nvs_flash_erase_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_erase_AddCallback(CMOCK_nvs_flash_erase_CALLBACK Callback)
{
  Mock.nvs_flash_erase_IgnoreBool = (char)0;
  Mock.nvs_flash_erase_CallbackBool = (char)1;
  Mock.nvs_flash_erase_CallbackFunctionPointer = Callback;
}

void nvs_flash_erase_Stub(CMOCK_nvs_flash_erase_CALLBACK Callback)
{
  Mock.nvs_flash_erase_IgnoreBool = (char)0;
  Mock.nvs_flash_erase_CallbackBool = (char)0;
  Mock.nvs_flash_erase_CallbackFunctionPointer = Callback;
}

esp_err_t nvs_flash_erase_partition(const char* part_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_erase_partition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_erase_partition);
  cmock_call_instance = (CMOCK_nvs_flash_erase_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_erase_partition_CallInstance);
  Mock.nvs_flash_erase_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_erase_partition_CallInstance);
  if (Mock.nvs_flash_erase_partition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_erase_partition_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_erase_partition_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_erase_partition_CallbackBool &&
      Mock.nvs_flash_erase_partition_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_erase_partition_CallbackFunctionPointer(part_name, Mock.nvs_flash_erase_partition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_part_name)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_erase_partition,CMockString_part_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_part_name, part_name, cmock_line, CMockStringMismatch);
  }
  if (Mock.nvs_flash_erase_partition_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_erase_partition_CallbackFunctionPointer(part_name, Mock.nvs_flash_erase_partition_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_erase_partition(CMOCK_nvs_flash_erase_partition_CALL_INSTANCE* cmock_call_instance, const char* part_name);
void CMockExpectParameters_nvs_flash_erase_partition(CMOCK_nvs_flash_erase_partition_CALL_INSTANCE* cmock_call_instance, const char* part_name)
{
  cmock_call_instance->Expected_part_name = part_name;
  cmock_call_instance->IgnoreArg_part_name = 0;
}

void nvs_flash_erase_partition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_erase_partition_IgnoreBool = (char)1;
}

void nvs_flash_erase_partition_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_erase_partition_IgnoreBool)
    Mock.nvs_flash_erase_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_erase_partition_CallInstance);
  Mock.nvs_flash_erase_partition_IgnoreBool = (char)0;
}

void nvs_flash_erase_partition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* part_name, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_erase_partition(cmock_call_instance, part_name);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_erase_partition_AddCallback(CMOCK_nvs_flash_erase_partition_CALLBACK Callback)
{
  Mock.nvs_flash_erase_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_erase_partition_CallbackBool = (char)1;
  Mock.nvs_flash_erase_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_erase_partition_Stub(CMOCK_nvs_flash_erase_partition_CALLBACK Callback)
{
  Mock.nvs_flash_erase_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_erase_partition_CallbackBool = (char)0;
  Mock.nvs_flash_erase_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_erase_partition_CMockIgnoreArg_part_name(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_erase_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_erase_partition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_part_name = 1;
}

esp_err_t nvs_flash_erase_partition_ptr(const esp_partition_t* partition)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_erase_partition_ptr);
  cmock_call_instance = (CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_erase_partition_ptr_CallInstance);
  Mock.nvs_flash_erase_partition_ptr_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_erase_partition_ptr_CallInstance);
  if (Mock.nvs_flash_erase_partition_ptr_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_erase_partition_ptr_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_erase_partition_ptr_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_erase_partition_ptr_CallbackBool &&
      Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer(partition, Mock.nvs_flash_erase_partition_ptr_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_erase_partition_ptr,CMockString_partition);
    if (cmock_call_instance->Expected_partition == NULL)
      { UNITY_TEST_ASSERT_NULL(partition, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_partition), (void*)(partition), sizeof(const esp_partition_t), cmock_call_instance->Expected_partition_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer(partition, Mock.nvs_flash_erase_partition_ptr_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_erase_partition_ptr(CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth);
void CMockExpectParameters_nvs_flash_erase_partition_ptr(CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth)
{
  cmock_call_instance->Expected_partition = partition;
  cmock_call_instance->Expected_partition_Depth = partition_Depth;
  cmock_call_instance->IgnoreArg_partition = 0;
}

void nvs_flash_erase_partition_ptr_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_partition_ptr_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_partition_ptr_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)1;
}

void nvs_flash_erase_partition_ptr_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_erase_partition_ptr_IgnoreBool)
    Mock.nvs_flash_erase_partition_ptr_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_erase_partition_ptr_CallInstance);
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)0;
}

void nvs_flash_erase_partition_ptr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_partition_ptr_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_partition_ptr_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_erase_partition_ptr(cmock_call_instance, partition, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_erase_partition_ptr_AddCallback(CMOCK_nvs_flash_erase_partition_ptr_CALLBACK Callback)
{
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)0;
  Mock.nvs_flash_erase_partition_ptr_CallbackBool = (char)1;
  Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer = Callback;
}

void nvs_flash_erase_partition_ptr_Stub(CMOCK_nvs_flash_erase_partition_ptr_CALLBACK Callback)
{
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)0;
  Mock.nvs_flash_erase_partition_ptr_CallbackBool = (char)0;
  Mock.nvs_flash_erase_partition_ptr_CallbackFunctionPointer = Callback;
}

void nvs_flash_erase_partition_ptr_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, int partition_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE));
  CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_erase_partition_ptr_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_erase_partition_ptr_CallInstance, cmock_guts_index);
  Mock.nvs_flash_erase_partition_ptr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_erase_partition_ptr(cmock_call_instance, partition, partition_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void nvs_flash_erase_partition_ptr_CMockIgnoreArg_partition(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_erase_partition_ptr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_erase_partition_ptr_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition = 1;
}

esp_err_t nvs_flash_secure_init(nvs_sec_cfg_t* cfg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_secure_init);
  cmock_call_instance = (CMOCK_nvs_flash_secure_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_secure_init_CallInstance);
  Mock.nvs_flash_secure_init_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_secure_init_CallInstance);
  if (Mock.nvs_flash_secure_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_secure_init_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_secure_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_secure_init_CallbackBool &&
      Mock.nvs_flash_secure_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_secure_init_CallbackFunctionPointer(cfg, Mock.nvs_flash_secure_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_cfg)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_secure_init,CMockString_cfg);
    if (cmock_call_instance->Expected_cfg == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(nvs_sec_cfg_t), cmock_call_instance->Expected_cfg_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.nvs_flash_secure_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_secure_init_CallbackFunctionPointer(cfg, Mock.nvs_flash_secure_init_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_cfg_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(cfg, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)cfg, (void*)cmock_call_instance->ReturnThruPtr_cfg_Val,
      cmock_call_instance->ReturnThruPtr_cfg_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_secure_init(CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance, nvs_sec_cfg_t* cfg, int cfg_Depth);
void CMockExpectParameters_nvs_flash_secure_init(CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance, nvs_sec_cfg_t* cfg, int cfg_Depth)
{
  cmock_call_instance->Expected_cfg = cfg;
  cmock_call_instance->Expected_cfg_Depth = cfg_Depth;
  cmock_call_instance->IgnoreArg_cfg = 0;
  cmock_call_instance->ReturnThruPtr_cfg_Used = 0;
}

void nvs_flash_secure_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_secure_init_CALL_INSTANCE));
  CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_secure_init_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_secure_init_CallInstance, cmock_guts_index);
  Mock.nvs_flash_secure_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_secure_init_IgnoreBool = (char)1;
}

void nvs_flash_secure_init_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_secure_init_IgnoreBool)
    Mock.nvs_flash_secure_init_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_secure_init_CallInstance);
  Mock.nvs_flash_secure_init_IgnoreBool = (char)0;
}

void nvs_flash_secure_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, nvs_sec_cfg_t* cfg, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_secure_init_CALL_INSTANCE));
  CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_secure_init_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_secure_init_CallInstance, cmock_guts_index);
  Mock.nvs_flash_secure_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_secure_init(cmock_call_instance, cfg, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_secure_init_AddCallback(CMOCK_nvs_flash_secure_init_CALLBACK Callback)
{
  Mock.nvs_flash_secure_init_IgnoreBool = (char)0;
  Mock.nvs_flash_secure_init_CallbackBool = (char)1;
  Mock.nvs_flash_secure_init_CallbackFunctionPointer = Callback;
}

void nvs_flash_secure_init_Stub(CMOCK_nvs_flash_secure_init_CALLBACK Callback)
{
  Mock.nvs_flash_secure_init_IgnoreBool = (char)0;
  Mock.nvs_flash_secure_init_CallbackBool = (char)0;
  Mock.nvs_flash_secure_init_CallbackFunctionPointer = Callback;
}

void nvs_flash_secure_init_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, nvs_sec_cfg_t* cfg, int cfg_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_secure_init_CALL_INSTANCE));
  CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_secure_init_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_secure_init_CallInstance, cmock_guts_index);
  Mock.nvs_flash_secure_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_secure_init(cmock_call_instance, cfg, cfg_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void nvs_flash_secure_init_CMockReturnMemThruPtr_cfg(UNITY_LINE_TYPE cmock_line, nvs_sec_cfg_t* cfg, size_t cmock_size)
{
  CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_secure_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_cfg_Used = 1;
  cmock_call_instance->ReturnThruPtr_cfg_Val = cfg;
  cmock_call_instance->ReturnThruPtr_cfg_Size = cmock_size;
}

void nvs_flash_secure_init_CMockIgnoreArg_cfg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_secure_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_secure_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg = 1;
}

esp_err_t nvs_flash_secure_init_partition(const char* partition_label, nvs_sec_cfg_t* cfg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_secure_init_partition);
  cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_secure_init_partition_CallInstance);
  Mock.nvs_flash_secure_init_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_secure_init_partition_CallInstance);
  if (Mock.nvs_flash_secure_init_partition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_secure_init_partition_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_secure_init_partition_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_secure_init_partition_CallbackBool &&
      Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer(partition_label, cfg, Mock.nvs_flash_secure_init_partition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition_label)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_secure_init_partition,CMockString_partition_label);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_partition_label, partition_label, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cfg)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_secure_init_partition,CMockString_cfg);
    if (cmock_call_instance->Expected_cfg == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(nvs_sec_cfg_t), cmock_call_instance->Expected_cfg_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer(partition_label, cfg, Mock.nvs_flash_secure_init_partition_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_cfg_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(cfg, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)cfg, (void*)cmock_call_instance->ReturnThruPtr_cfg_Val,
      cmock_call_instance->ReturnThruPtr_cfg_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_secure_init_partition(CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance, const char* partition_label, nvs_sec_cfg_t* cfg, int cfg_Depth);
void CMockExpectParameters_nvs_flash_secure_init_partition(CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance, const char* partition_label, nvs_sec_cfg_t* cfg, int cfg_Depth)
{
  cmock_call_instance->Expected_partition_label = partition_label;
  cmock_call_instance->IgnoreArg_partition_label = 0;
  cmock_call_instance->Expected_cfg = cfg;
  cmock_call_instance->Expected_cfg_Depth = cfg_Depth;
  cmock_call_instance->IgnoreArg_cfg = 0;
  cmock_call_instance->ReturnThruPtr_cfg_Used = 0;
}

void nvs_flash_secure_init_partition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_secure_init_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_secure_init_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)1;
}

void nvs_flash_secure_init_partition_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_secure_init_partition_IgnoreBool)
    Mock.nvs_flash_secure_init_partition_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_secure_init_partition_CallInstance);
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)0;
}

void nvs_flash_secure_init_partition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* partition_label, nvs_sec_cfg_t* cfg, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_secure_init_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_secure_init_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_secure_init_partition(cmock_call_instance, partition_label, cfg, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_secure_init_partition_AddCallback(CMOCK_nvs_flash_secure_init_partition_CALLBACK Callback)
{
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_secure_init_partition_CallbackBool = (char)1;
  Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_secure_init_partition_Stub(CMOCK_nvs_flash_secure_init_partition_CALLBACK Callback)
{
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)0;
  Mock.nvs_flash_secure_init_partition_CallbackBool = (char)0;
  Mock.nvs_flash_secure_init_partition_CallbackFunctionPointer = Callback;
}

void nvs_flash_secure_init_partition_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const char* partition_label, nvs_sec_cfg_t* cfg, int cfg_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE));
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_secure_init_partition_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_secure_init_partition_CallInstance, cmock_guts_index);
  Mock.nvs_flash_secure_init_partition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_secure_init_partition(cmock_call_instance, partition_label, cfg, cfg_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void nvs_flash_secure_init_partition_CMockReturnMemThruPtr_cfg(UNITY_LINE_TYPE cmock_line, nvs_sec_cfg_t* cfg, size_t cmock_size)
{
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_secure_init_partition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_cfg_Used = 1;
  cmock_call_instance->ReturnThruPtr_cfg_Val = cfg;
  cmock_call_instance->ReturnThruPtr_cfg_Size = cmock_size;
}

void nvs_flash_secure_init_partition_CMockIgnoreArg_partition_label(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_secure_init_partition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition_label = 1;
}

void nvs_flash_secure_init_partition_CMockIgnoreArg_cfg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_secure_init_partition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_secure_init_partition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg = 1;
}

esp_err_t nvs_flash_generate_keys(const esp_partition_t* partition, nvs_sec_cfg_t* cfg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_generate_keys);
  cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_generate_keys_CallInstance);
  Mock.nvs_flash_generate_keys_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_generate_keys_CallInstance);
  if (Mock.nvs_flash_generate_keys_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_generate_keys_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_generate_keys_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_generate_keys_CallbackBool &&
      Mock.nvs_flash_generate_keys_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_generate_keys_CallbackFunctionPointer(partition, cfg, Mock.nvs_flash_generate_keys_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_generate_keys,CMockString_partition);
    if (cmock_call_instance->Expected_partition == NULL)
      { UNITY_TEST_ASSERT_NULL(partition, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_partition), (void*)(partition), sizeof(const esp_partition_t), cmock_call_instance->Expected_partition_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_cfg)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_generate_keys,CMockString_cfg);
    if (cmock_call_instance->Expected_cfg == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(nvs_sec_cfg_t), cmock_call_instance->Expected_cfg_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.nvs_flash_generate_keys_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_generate_keys_CallbackFunctionPointer(partition, cfg, Mock.nvs_flash_generate_keys_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_cfg_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(cfg, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)cfg, (void*)cmock_call_instance->ReturnThruPtr_cfg_Val,
      cmock_call_instance->ReturnThruPtr_cfg_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_generate_keys(CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth, nvs_sec_cfg_t* cfg, int cfg_Depth);
void CMockExpectParameters_nvs_flash_generate_keys(CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth, nvs_sec_cfg_t* cfg, int cfg_Depth)
{
  cmock_call_instance->Expected_partition = partition;
  cmock_call_instance->Expected_partition_Depth = partition_Depth;
  cmock_call_instance->IgnoreArg_partition = 0;
  cmock_call_instance->Expected_cfg = cfg;
  cmock_call_instance->Expected_cfg_Depth = cfg_Depth;
  cmock_call_instance->IgnoreArg_cfg = 0;
  cmock_call_instance->ReturnThruPtr_cfg_Used = 0;
}

void nvs_flash_generate_keys_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_generate_keys_CALL_INSTANCE));
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_generate_keys_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_generate_keys_CallInstance, cmock_guts_index);
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)1;
}

void nvs_flash_generate_keys_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_generate_keys_IgnoreBool)
    Mock.nvs_flash_generate_keys_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_generate_keys_CallInstance);
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)0;
}

void nvs_flash_generate_keys_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, nvs_sec_cfg_t* cfg, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_generate_keys_CALL_INSTANCE));
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_generate_keys_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_generate_keys_CallInstance, cmock_guts_index);
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_generate_keys(cmock_call_instance, partition, 1, cfg, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_generate_keys_AddCallback(CMOCK_nvs_flash_generate_keys_CALLBACK Callback)
{
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)0;
  Mock.nvs_flash_generate_keys_CallbackBool = (char)1;
  Mock.nvs_flash_generate_keys_CallbackFunctionPointer = Callback;
}

void nvs_flash_generate_keys_Stub(CMOCK_nvs_flash_generate_keys_CALLBACK Callback)
{
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)0;
  Mock.nvs_flash_generate_keys_CallbackBool = (char)0;
  Mock.nvs_flash_generate_keys_CallbackFunctionPointer = Callback;
}

void nvs_flash_generate_keys_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, int partition_Depth, nvs_sec_cfg_t* cfg, int cfg_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_generate_keys_CALL_INSTANCE));
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_generate_keys_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_generate_keys_CallInstance, cmock_guts_index);
  Mock.nvs_flash_generate_keys_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_generate_keys(cmock_call_instance, partition, partition_Depth, cfg, cfg_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void nvs_flash_generate_keys_CMockReturnMemThruPtr_cfg(UNITY_LINE_TYPE cmock_line, nvs_sec_cfg_t* cfg, size_t cmock_size)
{
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_generate_keys_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_cfg_Used = 1;
  cmock_call_instance->ReturnThruPtr_cfg_Val = cfg;
  cmock_call_instance->ReturnThruPtr_cfg_Size = cmock_size;
}

void nvs_flash_generate_keys_CMockIgnoreArg_partition(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_generate_keys_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition = 1;
}

void nvs_flash_generate_keys_CMockIgnoreArg_cfg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_generate_keys_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_generate_keys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_generate_keys_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg = 1;
}

esp_err_t nvs_flash_read_security_cfg(const esp_partition_t* partition, nvs_sec_cfg_t* cfg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nvs_flash_read_security_cfg);
  cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nvs_flash_read_security_cfg_CallInstance);
  Mock.nvs_flash_read_security_cfg_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_read_security_cfg_CallInstance);
  if (Mock.nvs_flash_read_security_cfg_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.nvs_flash_read_security_cfg_FinalReturn;
    memcpy((void*)(&Mock.nvs_flash_read_security_cfg_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.nvs_flash_read_security_cfg_CallbackBool &&
      Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer(partition, cfg, Mock.nvs_flash_read_security_cfg_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_partition)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_read_security_cfg,CMockString_partition);
    if (cmock_call_instance->Expected_partition == NULL)
      { UNITY_TEST_ASSERT_NULL(partition, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_partition), (void*)(partition), sizeof(const esp_partition_t), cmock_call_instance->Expected_partition_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_cfg)
  {
    UNITY_SET_DETAILS(CMockString_nvs_flash_read_security_cfg,CMockString_cfg);
    if (cmock_call_instance->Expected_cfg == NULL)
      { UNITY_TEST_ASSERT_NULL(cfg, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cfg), (void*)(cfg), sizeof(nvs_sec_cfg_t), cmock_call_instance->Expected_cfg_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer(partition, cfg, Mock.nvs_flash_read_security_cfg_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_cfg_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(cfg, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)cfg, (void*)cmock_call_instance->ReturnThruPtr_cfg_Val,
      cmock_call_instance->ReturnThruPtr_cfg_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_nvs_flash_read_security_cfg(CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth, nvs_sec_cfg_t* cfg, int cfg_Depth);
void CMockExpectParameters_nvs_flash_read_security_cfg(CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance, const esp_partition_t* partition, int partition_Depth, nvs_sec_cfg_t* cfg, int cfg_Depth)
{
  cmock_call_instance->Expected_partition = partition;
  cmock_call_instance->Expected_partition_Depth = partition_Depth;
  cmock_call_instance->IgnoreArg_partition = 0;
  cmock_call_instance->Expected_cfg = cfg;
  cmock_call_instance->Expected_cfg_Depth = cfg_Depth;
  cmock_call_instance->IgnoreArg_cfg = 0;
  cmock_call_instance->ReturnThruPtr_cfg_Used = 0;
}

void nvs_flash_read_security_cfg_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE));
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_read_security_cfg_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_read_security_cfg_CallInstance, cmock_guts_index);
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)1;
}

void nvs_flash_read_security_cfg_CMockStopIgnore(void)
{
  if(Mock.nvs_flash_read_security_cfg_IgnoreBool)
    Mock.nvs_flash_read_security_cfg_CallInstance = CMock_Guts_MemNext(Mock.nvs_flash_read_security_cfg_CallInstance);
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)0;
}

void nvs_flash_read_security_cfg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, nvs_sec_cfg_t* cfg, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE));
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_read_security_cfg_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_read_security_cfg_CallInstance, cmock_guts_index);
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_read_security_cfg(cmock_call_instance, partition, 1, cfg, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void nvs_flash_read_security_cfg_AddCallback(CMOCK_nvs_flash_read_security_cfg_CALLBACK Callback)
{
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)0;
  Mock.nvs_flash_read_security_cfg_CallbackBool = (char)1;
  Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer = Callback;
}

void nvs_flash_read_security_cfg_Stub(CMOCK_nvs_flash_read_security_cfg_CALLBACK Callback)
{
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)0;
  Mock.nvs_flash_read_security_cfg_CallbackBool = (char)0;
  Mock.nvs_flash_read_security_cfg_CallbackFunctionPointer = Callback;
}

void nvs_flash_read_security_cfg_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const esp_partition_t* partition, int partition_Depth, nvs_sec_cfg_t* cfg, int cfg_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE));
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nvs_flash_read_security_cfg_CallInstance = CMock_Guts_MemChain(Mock.nvs_flash_read_security_cfg_CallInstance, cmock_guts_index);
  Mock.nvs_flash_read_security_cfg_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nvs_flash_read_security_cfg(cmock_call_instance, partition, partition_Depth, cfg, cfg_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void nvs_flash_read_security_cfg_CMockReturnMemThruPtr_cfg(UNITY_LINE_TYPE cmock_line, nvs_sec_cfg_t* cfg, size_t cmock_size)
{
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_read_security_cfg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_cfg_Used = 1;
  cmock_call_instance->ReturnThruPtr_cfg_Val = cfg;
  cmock_call_instance->ReturnThruPtr_cfg_Size = cmock_size;
}

void nvs_flash_read_security_cfg_CMockIgnoreArg_partition(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_read_security_cfg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_partition = 1;
}

void nvs_flash_read_security_cfg_CMockIgnoreArg_cfg(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE* cmock_call_instance = (CMOCK_nvs_flash_read_security_cfg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nvs_flash_read_security_cfg_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cfg = 1;
}

