/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_semaphore.h"

static const char* CMockString_init_count = "init_count";
static const char* CMockString_max_count = "max_count";
static const char* CMockString_osi_sem_free = "osi_sem_free";
static const char* CMockString_osi_sem_give = "osi_sem_give";
static const char* CMockString_osi_sem_new = "osi_sem_new";
static const char* CMockString_osi_sem_take = "osi_sem_take";
static const char* CMockString_sem = "sem";
static const char* CMockString_timeout = "timeout";

typedef struct _CMOCK_osi_sem_new_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  osi_sem_t* Expected_sem;
  uint32_t Expected_max_count;
  uint32_t Expected_init_count;
  int Expected_sem_Depth;
  char ReturnThruPtr_sem_Used;
  osi_sem_t* ReturnThruPtr_sem_Val;
  size_t ReturnThruPtr_sem_Size;
  char IgnoreArg_sem;
  char IgnoreArg_max_count;
  char IgnoreArg_init_count;

} CMOCK_osi_sem_new_CALL_INSTANCE;

typedef struct _CMOCK_osi_sem_free_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  osi_sem_t* Expected_sem;
  int Expected_sem_Depth;
  char ReturnThruPtr_sem_Used;
  osi_sem_t* ReturnThruPtr_sem_Val;
  size_t ReturnThruPtr_sem_Size;
  char IgnoreArg_sem;

} CMOCK_osi_sem_free_CALL_INSTANCE;

typedef struct _CMOCK_osi_sem_take_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  int CallOrder;
  osi_sem_t* Expected_sem;
  uint32_t Expected_timeout;
  int Expected_sem_Depth;
  char ReturnThruPtr_sem_Used;
  osi_sem_t* ReturnThruPtr_sem_Val;
  size_t ReturnThruPtr_sem_Size;
  char IgnoreArg_sem;
  char IgnoreArg_timeout;

} CMOCK_osi_sem_take_CALL_INSTANCE;

typedef struct _CMOCK_osi_sem_give_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  osi_sem_t* Expected_sem;
  int Expected_sem_Depth;
  char ReturnThruPtr_sem_Used;
  osi_sem_t* ReturnThruPtr_sem_Val;
  size_t ReturnThruPtr_sem_Size;
  char IgnoreArg_sem;

} CMOCK_osi_sem_give_CALL_INSTANCE;

static struct mock_semaphoreInstance
{
  char osi_sem_new_IgnoreBool;
  int osi_sem_new_FinalReturn;
  char osi_sem_new_CallbackBool;
  CMOCK_osi_sem_new_CALLBACK osi_sem_new_CallbackFunctionPointer;
  int osi_sem_new_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osi_sem_new_CallInstance;
  char osi_sem_free_IgnoreBool;
  int osi_sem_free_FinalReturn;
  char osi_sem_free_CallbackBool;
  CMOCK_osi_sem_free_CALLBACK osi_sem_free_CallbackFunctionPointer;
  int osi_sem_free_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osi_sem_free_CallInstance;
  char osi_sem_take_IgnoreBool;
  int osi_sem_take_FinalReturn;
  char osi_sem_take_CallbackBool;
  CMOCK_osi_sem_take_CALLBACK osi_sem_take_CallbackFunctionPointer;
  int osi_sem_take_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osi_sem_take_CallInstance;
  char osi_sem_give_IgnoreBool;
  char osi_sem_give_CallbackBool;
  CMOCK_osi_sem_give_CALLBACK osi_sem_give_CallbackFunctionPointer;
  int osi_sem_give_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osi_sem_give_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_semaphore_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.osi_sem_new_CallInstance;
  if (Mock.osi_sem_new_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osi_sem_new);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osi_sem_new_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osi_sem_free_CallInstance;
  if (Mock.osi_sem_free_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osi_sem_free);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osi_sem_free_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osi_sem_take_CallInstance;
  if (Mock.osi_sem_take_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osi_sem_take);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osi_sem_take_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osi_sem_give_CallInstance;
  if (Mock.osi_sem_give_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osi_sem_give);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osi_sem_give_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_semaphore_Init(void)
{
  mock_semaphore_Destroy();
}

void mock_semaphore_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

int osi_sem_new(osi_sem_t* sem, uint32_t max_count, uint32_t init_count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osi_sem_new);
  cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osi_sem_new_CallInstance);
  Mock.osi_sem_new_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_new_CallInstance);
  if (Mock.osi_sem_new_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osi_sem_new_FinalReturn;
    Mock.osi_sem_new_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osi_sem_new_CallbackBool &&
      Mock.osi_sem_new_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.osi_sem_new_CallbackFunctionPointer(sem, max_count, init_count, Mock.osi_sem_new_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_new,CMockString_sem);
    if (cmock_call_instance->Expected_sem == NULL)
      { UNITY_TEST_ASSERT_NULL(sem, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_sem), (void*)(sem), sizeof(osi_sem_t), cmock_call_instance->Expected_sem_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_max_count)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_new,CMockString_max_count);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_max_count, max_count, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_init_count)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_new,CMockString_init_count);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_init_count, init_count, cmock_line, CMockStringMismatch);
  }
  if (Mock.osi_sem_new_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.osi_sem_new_CallbackFunctionPointer(sem, max_count, init_count, Mock.osi_sem_new_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_sem_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(sem, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)sem, (void*)cmock_call_instance->ReturnThruPtr_sem_Val,
      cmock_call_instance->ReturnThruPtr_sem_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osi_sem_new(CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth, uint32_t max_count, uint32_t init_count);
void CMockExpectParameters_osi_sem_new(CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth, uint32_t max_count, uint32_t init_count)
{
  cmock_call_instance->Expected_sem = sem;
  cmock_call_instance->Expected_sem_Depth = sem_Depth;
  cmock_call_instance->IgnoreArg_sem = 0;
  cmock_call_instance->ReturnThruPtr_sem_Used = 0;
  cmock_call_instance->Expected_max_count = max_count;
  cmock_call_instance->IgnoreArg_max_count = 0;
  cmock_call_instance->Expected_init_count = init_count;
  cmock_call_instance->IgnoreArg_init_count = 0;
}

void osi_sem_new_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_new_CALL_INSTANCE));
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_new_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_new_CallInstance, cmock_guts_index);
  Mock.osi_sem_new_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osi_sem_new_IgnoreBool = (char)1;
}

void osi_sem_new_CMockStopIgnore(void)
{
  if(Mock.osi_sem_new_IgnoreBool)
    Mock.osi_sem_new_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_new_CallInstance);
  Mock.osi_sem_new_IgnoreBool = (char)0;
}

void osi_sem_new_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, uint32_t max_count, uint32_t init_count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_new_CALL_INSTANCE));
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_new_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_new_CallInstance, cmock_guts_index);
  Mock.osi_sem_new_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_new(cmock_call_instance, sem, 1, max_count, init_count);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osi_sem_new_AddCallback(CMOCK_osi_sem_new_CALLBACK Callback)
{
  Mock.osi_sem_new_IgnoreBool = (char)0;
  Mock.osi_sem_new_CallbackBool = (char)1;
  Mock.osi_sem_new_CallbackFunctionPointer = Callback;
}

void osi_sem_new_Stub(CMOCK_osi_sem_new_CALLBACK Callback)
{
  Mock.osi_sem_new_IgnoreBool = (char)0;
  Mock.osi_sem_new_CallbackBool = (char)0;
  Mock.osi_sem_new_CallbackFunctionPointer = Callback;
}

void osi_sem_new_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, int sem_Depth, uint32_t max_count, uint32_t init_count, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_new_CALL_INSTANCE));
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_new_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_new_CallInstance, cmock_guts_index);
  Mock.osi_sem_new_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_new(cmock_call_instance, sem, sem_Depth, max_count, init_count);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osi_sem_new_CMockReturnMemThruPtr_sem(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, size_t cmock_size)
{
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_new_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_sem_Used = 1;
  cmock_call_instance->ReturnThruPtr_sem_Val = sem;
  cmock_call_instance->ReturnThruPtr_sem_Size = cmock_size;
}

void osi_sem_new_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_new_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

void osi_sem_new_CMockIgnoreArg_max_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_new_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_max_count = 1;
}

void osi_sem_new_CMockIgnoreArg_init_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_new_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_new_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_new_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_init_count = 1;
}

int osi_sem_free(osi_sem_t* sem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osi_sem_free);
  cmock_call_instance = (CMOCK_osi_sem_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osi_sem_free_CallInstance);
  Mock.osi_sem_free_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_free_CallInstance);
  if (Mock.osi_sem_free_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osi_sem_free_FinalReturn;
    Mock.osi_sem_free_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osi_sem_free_CallbackBool &&
      Mock.osi_sem_free_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.osi_sem_free_CallbackFunctionPointer(sem, Mock.osi_sem_free_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_free,CMockString_sem);
    if (cmock_call_instance->Expected_sem == NULL)
      { UNITY_TEST_ASSERT_NULL(sem, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_sem), (void*)(sem), sizeof(osi_sem_t), cmock_call_instance->Expected_sem_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.osi_sem_free_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.osi_sem_free_CallbackFunctionPointer(sem, Mock.osi_sem_free_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_sem_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(sem, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)sem, (void*)cmock_call_instance->ReturnThruPtr_sem_Val,
      cmock_call_instance->ReturnThruPtr_sem_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osi_sem_free(CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth);
void CMockExpectParameters_osi_sem_free(CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth)
{
  cmock_call_instance->Expected_sem = sem;
  cmock_call_instance->Expected_sem_Depth = sem_Depth;
  cmock_call_instance->IgnoreArg_sem = 0;
  cmock_call_instance->ReturnThruPtr_sem_Used = 0;
}

void osi_sem_free_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_free_CALL_INSTANCE));
  CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_free_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_free_CallInstance, cmock_guts_index);
  Mock.osi_sem_free_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osi_sem_free_IgnoreBool = (char)1;
}

void osi_sem_free_CMockStopIgnore(void)
{
  if(Mock.osi_sem_free_IgnoreBool)
    Mock.osi_sem_free_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_free_CallInstance);
  Mock.osi_sem_free_IgnoreBool = (char)0;
}

void osi_sem_free_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_free_CALL_INSTANCE));
  CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_free_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_free_CallInstance, cmock_guts_index);
  Mock.osi_sem_free_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_free(cmock_call_instance, sem, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osi_sem_free_AddCallback(CMOCK_osi_sem_free_CALLBACK Callback)
{
  Mock.osi_sem_free_IgnoreBool = (char)0;
  Mock.osi_sem_free_CallbackBool = (char)1;
  Mock.osi_sem_free_CallbackFunctionPointer = Callback;
}

void osi_sem_free_Stub(CMOCK_osi_sem_free_CALLBACK Callback)
{
  Mock.osi_sem_free_IgnoreBool = (char)0;
  Mock.osi_sem_free_CallbackBool = (char)0;
  Mock.osi_sem_free_CallbackFunctionPointer = Callback;
}

void osi_sem_free_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, int sem_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_free_CALL_INSTANCE));
  CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_free_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_free_CallInstance, cmock_guts_index);
  Mock.osi_sem_free_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_free(cmock_call_instance, sem, sem_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osi_sem_free_CMockReturnMemThruPtr_sem(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, size_t cmock_size)
{
  CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_free_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_sem_Used = 1;
  cmock_call_instance->ReturnThruPtr_sem_Val = sem;
  cmock_call_instance->ReturnThruPtr_sem_Size = cmock_size;
}

void osi_sem_free_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_free_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_free_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_free_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

int osi_sem_take(osi_sem_t* sem, uint32_t timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osi_sem_take);
  cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osi_sem_take_CallInstance);
  Mock.osi_sem_take_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_take_CallInstance);
  if (Mock.osi_sem_take_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osi_sem_take_FinalReturn;
    Mock.osi_sem_take_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osi_sem_take_CallbackBool &&
      Mock.osi_sem_take_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.osi_sem_take_CallbackFunctionPointer(sem, timeout, Mock.osi_sem_take_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_take,CMockString_sem);
    if (cmock_call_instance->Expected_sem == NULL)
      { UNITY_TEST_ASSERT_NULL(sem, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_sem), (void*)(sem), sizeof(osi_sem_t), cmock_call_instance->Expected_sem_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_take,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout, timeout, cmock_line, CMockStringMismatch);
  }
  if (Mock.osi_sem_take_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.osi_sem_take_CallbackFunctionPointer(sem, timeout, Mock.osi_sem_take_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_sem_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(sem, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)sem, (void*)cmock_call_instance->ReturnThruPtr_sem_Val,
      cmock_call_instance->ReturnThruPtr_sem_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osi_sem_take(CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth, uint32_t timeout);
void CMockExpectParameters_osi_sem_take(CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth, uint32_t timeout)
{
  cmock_call_instance->Expected_sem = sem;
  cmock_call_instance->Expected_sem_Depth = sem_Depth;
  cmock_call_instance->IgnoreArg_sem = 0;
  cmock_call_instance->ReturnThruPtr_sem_Used = 0;
  cmock_call_instance->Expected_timeout = timeout;
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void osi_sem_take_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_take_CALL_INSTANCE));
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_take_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_take_CallInstance, cmock_guts_index);
  Mock.osi_sem_take_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osi_sem_take_IgnoreBool = (char)1;
}

void osi_sem_take_CMockStopIgnore(void)
{
  if(Mock.osi_sem_take_IgnoreBool)
    Mock.osi_sem_take_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_take_CallInstance);
  Mock.osi_sem_take_IgnoreBool = (char)0;
}

void osi_sem_take_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, uint32_t timeout, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_take_CALL_INSTANCE));
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_take_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_take_CallInstance, cmock_guts_index);
  Mock.osi_sem_take_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_take(cmock_call_instance, sem, 1, timeout);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osi_sem_take_AddCallback(CMOCK_osi_sem_take_CALLBACK Callback)
{
  Mock.osi_sem_take_IgnoreBool = (char)0;
  Mock.osi_sem_take_CallbackBool = (char)1;
  Mock.osi_sem_take_CallbackFunctionPointer = Callback;
}

void osi_sem_take_Stub(CMOCK_osi_sem_take_CALLBACK Callback)
{
  Mock.osi_sem_take_IgnoreBool = (char)0;
  Mock.osi_sem_take_CallbackBool = (char)0;
  Mock.osi_sem_take_CallbackFunctionPointer = Callback;
}

void osi_sem_take_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, int sem_Depth, uint32_t timeout, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_take_CALL_INSTANCE));
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_take_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_take_CallInstance, cmock_guts_index);
  Mock.osi_sem_take_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_take(cmock_call_instance, sem, sem_Depth, timeout);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osi_sem_take_CMockReturnMemThruPtr_sem(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, size_t cmock_size)
{
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_take_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_sem_Used = 1;
  cmock_call_instance->ReturnThruPtr_sem_Val = sem;
  cmock_call_instance->ReturnThruPtr_sem_Size = cmock_size;
}

void osi_sem_take_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_take_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

void osi_sem_take_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_take_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_take_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

void osi_sem_give(osi_sem_t* sem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osi_sem_give);
  cmock_call_instance = (CMOCK_osi_sem_give_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osi_sem_give_CallInstance);
  Mock.osi_sem_give_CallInstance = CMock_Guts_MemNext(Mock.osi_sem_give_CallInstance);
  if (Mock.osi_sem_give_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.osi_sem_give_CallbackBool &&
      Mock.osi_sem_give_CallbackFunctionPointer != NULL)
  {
    Mock.osi_sem_give_CallbackFunctionPointer(sem, Mock.osi_sem_give_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_sem)
  {
    UNITY_SET_DETAILS(CMockString_osi_sem_give,CMockString_sem);
    if (cmock_call_instance->Expected_sem == NULL)
      { UNITY_TEST_ASSERT_NULL(sem, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_sem), (void*)(sem), sizeof(osi_sem_t), cmock_call_instance->Expected_sem_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.osi_sem_give_CallbackFunctionPointer != NULL)
  {
    Mock.osi_sem_give_CallbackFunctionPointer(sem, Mock.osi_sem_give_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_sem_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(sem, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)sem, (void*)cmock_call_instance->ReturnThruPtr_sem_Val,
      cmock_call_instance->ReturnThruPtr_sem_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_osi_sem_give(CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth);
void CMockExpectParameters_osi_sem_give(CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance, osi_sem_t* sem, int sem_Depth)
{
  cmock_call_instance->Expected_sem = sem;
  cmock_call_instance->Expected_sem_Depth = sem_Depth;
  cmock_call_instance->IgnoreArg_sem = 0;
  cmock_call_instance->ReturnThruPtr_sem_Used = 0;
}

void osi_sem_give_CMockIgnore(void)
{
  Mock.osi_sem_give_IgnoreBool = (char)1;
}

void osi_sem_give_CMockStopIgnore(void)
{
  Mock.osi_sem_give_IgnoreBool = (char)0;
}

void osi_sem_give_CMockExpect(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_give_CALL_INSTANCE));
  CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_give_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_give_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_give_CallInstance, cmock_guts_index);
  Mock.osi_sem_give_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_give(cmock_call_instance, sem, 1);
}

void osi_sem_give_AddCallback(CMOCK_osi_sem_give_CALLBACK Callback)
{
  Mock.osi_sem_give_IgnoreBool = (char)0;
  Mock.osi_sem_give_CallbackBool = (char)1;
  Mock.osi_sem_give_CallbackFunctionPointer = Callback;
}

void osi_sem_give_Stub(CMOCK_osi_sem_give_CALLBACK Callback)
{
  Mock.osi_sem_give_IgnoreBool = (char)0;
  Mock.osi_sem_give_CallbackBool = (char)0;
  Mock.osi_sem_give_CallbackFunctionPointer = Callback;
}

void osi_sem_give_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, int sem_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osi_sem_give_CALL_INSTANCE));
  CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_give_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osi_sem_give_CallInstance = CMock_Guts_MemChain(Mock.osi_sem_give_CallInstance, cmock_guts_index);
  Mock.osi_sem_give_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_osi_sem_give(cmock_call_instance, sem, sem_Depth);
}

void osi_sem_give_CMockReturnMemThruPtr_sem(UNITY_LINE_TYPE cmock_line, osi_sem_t* sem, size_t cmock_size)
{
  CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_give_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_give_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_sem_Used = 1;
  cmock_call_instance->ReturnThruPtr_sem_Val = sem;
  cmock_call_instance->ReturnThruPtr_sem_Size = cmock_size;
}

void osi_sem_give_CMockIgnoreArg_sem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osi_sem_give_CALL_INSTANCE* cmock_call_instance = (CMOCK_osi_sem_give_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osi_sem_give_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sem = 1;
}

