/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_esp_wifi_default.h"

#include "esp_netif_lwip_internal.h"

static const char* CMockString_esp_netif = "esp_netif";
static const char* CMockString_esp_netif_attach_wifi_ap = "esp_netif_attach_wifi_ap";
static const char* CMockString_esp_netif_attach_wifi_station = "esp_netif_attach_wifi_station";
static const char* CMockString_esp_netif_config = "esp_netif_config";
static const char* CMockString_esp_netif_create_default_wifi_ap = "esp_netif_create_default_wifi_ap";
static const char* CMockString_esp_netif_create_default_wifi_mesh_netifs = "esp_netif_create_default_wifi_mesh_netifs";
static const char* CMockString_esp_netif_create_default_wifi_sta = "esp_netif_create_default_wifi_sta";
static const char* CMockString_esp_netif_create_wifi = "esp_netif_create_wifi";
static const char* CMockString_esp_netif_destroy_default_wifi = "esp_netif_destroy_default_wifi";
static const char* CMockString_esp_wifi_clear_default_wifi_driver_and_handlers = "esp_wifi_clear_default_wifi_driver_and_handlers";
static const char* CMockString_esp_wifi_set_default_wifi_ap_handlers = "esp_wifi_set_default_wifi_ap_handlers";
static const char* CMockString_esp_wifi_set_default_wifi_sta_handlers = "esp_wifi_set_default_wifi_sta_handlers";
static const char* CMockString_p_netif_ap = "p_netif_ap";
static const char* CMockString_p_netif_sta = "p_netif_sta";
static const char* CMockString_wifi_if = "wifi_if";

typedef struct _CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_netif_t* Expected_esp_netif;
  int Expected_esp_netif_Depth;
  char ReturnThruPtr_esp_netif_Used;
  esp_netif_t* ReturnThruPtr_esp_netif_Val;
  size_t ReturnThruPtr_esp_netif_Size;
  char IgnoreArg_esp_netif;

} CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE;

typedef struct _CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_netif_t* Expected_esp_netif;
  int Expected_esp_netif_Depth;
  char ReturnThruPtr_esp_netif_Used;
  esp_netif_t* ReturnThruPtr_esp_netif_Val;
  size_t ReturnThruPtr_esp_netif_Size;
  char IgnoreArg_esp_netif;

} CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE;

typedef struct _CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE;

typedef struct _CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;

} CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE;

typedef struct _CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  void* Expected_esp_netif;
  int Expected_esp_netif_Depth;
  char ReturnThruPtr_esp_netif_Used;
  void* ReturnThruPtr_esp_netif_Val;
  size_t ReturnThruPtr_esp_netif_Size;
  char IgnoreArg_esp_netif;

} CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE;

typedef struct _CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_netif_t* ReturnVal;
  int CallOrder;

} CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE;

typedef struct _CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_netif_t* ReturnVal;
  int CallOrder;

} CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE;

typedef struct _CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  void* Expected_esp_netif;
  int Expected_esp_netif_Depth;
  char ReturnThruPtr_esp_netif_Used;
  void* ReturnThruPtr_esp_netif_Val;
  size_t ReturnThruPtr_esp_netif_Size;
  char IgnoreArg_esp_netif;

} CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE;

typedef struct _CMOCK_esp_netif_create_wifi_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_netif_t* ReturnVal;
  int CallOrder;
  wifi_interface_t Expected_wifi_if;
  esp_netif_inherent_config_t* Expected_esp_netif_config;
  int Expected_esp_netif_config_Depth;
  char ReturnThruPtr_esp_netif_config_Used;
  esp_netif_inherent_config_t* ReturnThruPtr_esp_netif_config_Val;
  size_t ReturnThruPtr_esp_netif_config_Size;
  char IgnoreArg_wifi_if;
  char IgnoreArg_esp_netif_config;

} CMOCK_esp_netif_create_wifi_CALL_INSTANCE;

typedef struct _CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  esp_netif_t** Expected_p_netif_sta;
  esp_netif_t** Expected_p_netif_ap;
  int Expected_p_netif_sta_Depth;
  int Expected_p_netif_ap_Depth;
  char ReturnThruPtr_p_netif_sta_Used;
  esp_netif_t** ReturnThruPtr_p_netif_sta_Val;
  size_t ReturnThruPtr_p_netif_sta_Size;
  char ReturnThruPtr_p_netif_ap_Used;
  esp_netif_t** ReturnThruPtr_p_netif_ap_Val;
  size_t ReturnThruPtr_p_netif_ap_Size;
  char IgnoreArg_p_netif_sta;
  char IgnoreArg_p_netif_ap;

} CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE;

static struct mock_esp_wifi_defaultInstance
{
  char esp_netif_attach_wifi_station_IgnoreBool;
  esp_err_t esp_netif_attach_wifi_station_FinalReturn;
  char esp_netif_attach_wifi_station_CallbackBool;
  CMOCK_esp_netif_attach_wifi_station_CALLBACK esp_netif_attach_wifi_station_CallbackFunctionPointer;
  int esp_netif_attach_wifi_station_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_attach_wifi_station_CallInstance;
  char esp_netif_attach_wifi_ap_IgnoreBool;
  esp_err_t esp_netif_attach_wifi_ap_FinalReturn;
  char esp_netif_attach_wifi_ap_CallbackBool;
  CMOCK_esp_netif_attach_wifi_ap_CALLBACK esp_netif_attach_wifi_ap_CallbackFunctionPointer;
  int esp_netif_attach_wifi_ap_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_attach_wifi_ap_CallInstance;
  char esp_wifi_set_default_wifi_sta_handlers_IgnoreBool;
  esp_err_t esp_wifi_set_default_wifi_sta_handlers_FinalReturn;
  char esp_wifi_set_default_wifi_sta_handlers_CallbackBool;
  CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALLBACK esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer;
  int esp_wifi_set_default_wifi_sta_handlers_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_wifi_set_default_wifi_sta_handlers_CallInstance;
  char esp_wifi_set_default_wifi_ap_handlers_IgnoreBool;
  esp_err_t esp_wifi_set_default_wifi_ap_handlers_FinalReturn;
  char esp_wifi_set_default_wifi_ap_handlers_CallbackBool;
  CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALLBACK esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer;
  int esp_wifi_set_default_wifi_ap_handlers_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_wifi_set_default_wifi_ap_handlers_CallInstance;
  char esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool;
  esp_err_t esp_wifi_clear_default_wifi_driver_and_handlers_FinalReturn;
  char esp_wifi_clear_default_wifi_driver_and_handlers_CallbackBool;
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALLBACK esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer;
  int esp_wifi_clear_default_wifi_driver_and_handlers_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance;
  char esp_netif_create_default_wifi_ap_IgnoreBool;
  esp_netif_t* esp_netif_create_default_wifi_ap_FinalReturn;
  char esp_netif_create_default_wifi_ap_CallbackBool;
  CMOCK_esp_netif_create_default_wifi_ap_CALLBACK esp_netif_create_default_wifi_ap_CallbackFunctionPointer;
  int esp_netif_create_default_wifi_ap_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_create_default_wifi_ap_CallInstance;
  char esp_netif_create_default_wifi_sta_IgnoreBool;
  esp_netif_t* esp_netif_create_default_wifi_sta_FinalReturn;
  char esp_netif_create_default_wifi_sta_CallbackBool;
  CMOCK_esp_netif_create_default_wifi_sta_CALLBACK esp_netif_create_default_wifi_sta_CallbackFunctionPointer;
  int esp_netif_create_default_wifi_sta_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_create_default_wifi_sta_CallInstance;
  char esp_netif_destroy_default_wifi_IgnoreBool;
  char esp_netif_destroy_default_wifi_CallbackBool;
  CMOCK_esp_netif_destroy_default_wifi_CALLBACK esp_netif_destroy_default_wifi_CallbackFunctionPointer;
  int esp_netif_destroy_default_wifi_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_destroy_default_wifi_CallInstance;
  char esp_netif_create_wifi_IgnoreBool;
  esp_netif_t* esp_netif_create_wifi_FinalReturn;
  char esp_netif_create_wifi_CallbackBool;
  CMOCK_esp_netif_create_wifi_CALLBACK esp_netif_create_wifi_CallbackFunctionPointer;
  int esp_netif_create_wifi_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_create_wifi_CallInstance;
  char esp_netif_create_default_wifi_mesh_netifs_IgnoreBool;
  esp_err_t esp_netif_create_default_wifi_mesh_netifs_FinalReturn;
  char esp_netif_create_default_wifi_mesh_netifs_CallbackBool;
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALLBACK esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer;
  int esp_netif_create_default_wifi_mesh_netifs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_netif_create_default_wifi_mesh_netifs_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_esp_wifi_default_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.esp_netif_attach_wifi_station_CallInstance;
  if (Mock.esp_netif_attach_wifi_station_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_attach_wifi_station);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_netif_attach_wifi_ap_CallInstance;
  if (Mock.esp_netif_attach_wifi_ap_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_attach_wifi_ap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance;
  if (Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_wifi_set_default_wifi_sta_handlers);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance;
  if (Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_wifi_set_default_wifi_ap_handlers);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance;
  if (Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_wifi_clear_default_wifi_driver_and_handlers);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_netif_create_default_wifi_ap_CallInstance;
  if (Mock.esp_netif_create_default_wifi_ap_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_create_default_wifi_ap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_netif_create_default_wifi_sta_CallInstance;
  if (Mock.esp_netif_create_default_wifi_sta_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_create_default_wifi_sta);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_netif_destroy_default_wifi_CallInstance;
  if (Mock.esp_netif_destroy_default_wifi_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_destroy_default_wifi);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_netif_create_wifi_CallInstance;
  if (Mock.esp_netif_create_wifi_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_create_wifi);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_create_wifi_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance;
  if (Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_netif_create_default_wifi_mesh_netifs);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_esp_wifi_default_Init(void)
{
  mock_esp_wifi_default_Destroy();
}

void mock_esp_wifi_default_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t esp_netif_attach_wifi_station(esp_netif_t* esp_netif)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_attach_wifi_station);
  cmock_call_instance = (CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_attach_wifi_station_CallInstance);
  Mock.esp_netif_attach_wifi_station_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_attach_wifi_station_CallInstance);
  if (Mock.esp_netif_attach_wifi_station_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_netif_attach_wifi_station_FinalReturn;
    memcpy((void*)(&Mock.esp_netif_attach_wifi_station_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_netif_attach_wifi_station_CallbackBool &&
      Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer(esp_netif, Mock.esp_netif_attach_wifi_station_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_esp_netif)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_attach_wifi_station,CMockString_esp_netif);
    if (cmock_call_instance->Expected_esp_netif == NULL)
      { UNITY_TEST_ASSERT_NULL(esp_netif, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_esp_netif), (void*)(esp_netif), sizeof(esp_netif_t), cmock_call_instance->Expected_esp_netif_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer(esp_netif, Mock.esp_netif_attach_wifi_station_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_esp_netif_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(esp_netif, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)esp_netif, (void*)cmock_call_instance->ReturnThruPtr_esp_netif_Val,
      cmock_call_instance->ReturnThruPtr_esp_netif_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_netif_attach_wifi_station(CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance, esp_netif_t* esp_netif, int esp_netif_Depth);
void CMockExpectParameters_esp_netif_attach_wifi_station(CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance, esp_netif_t* esp_netif, int esp_netif_Depth)
{
  cmock_call_instance->Expected_esp_netif = esp_netif;
  cmock_call_instance->Expected_esp_netif_Depth = esp_netif_Depth;
  cmock_call_instance->IgnoreArg_esp_netif = 0;
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 0;
}

void esp_netif_attach_wifi_station_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE));
  CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_attach_wifi_station_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_attach_wifi_station_CallInstance, cmock_guts_index);
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)1;
}

void esp_netif_attach_wifi_station_CMockStopIgnore(void)
{
  if(Mock.esp_netif_attach_wifi_station_IgnoreBool)
    Mock.esp_netif_attach_wifi_station_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_attach_wifi_station_CallInstance);
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)0;
}

void esp_netif_attach_wifi_station_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* esp_netif, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE));
  CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_attach_wifi_station_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_attach_wifi_station_CallInstance, cmock_guts_index);
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_attach_wifi_station(cmock_call_instance, esp_netif, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_netif_attach_wifi_station_AddCallback(CMOCK_esp_netif_attach_wifi_station_CALLBACK Callback)
{
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)0;
  Mock.esp_netif_attach_wifi_station_CallbackBool = (char)1;
  Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer = Callback;
}

void esp_netif_attach_wifi_station_Stub(CMOCK_esp_netif_attach_wifi_station_CALLBACK Callback)
{
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)0;
  Mock.esp_netif_attach_wifi_station_CallbackBool = (char)0;
  Mock.esp_netif_attach_wifi_station_CallbackFunctionPointer = Callback;
}

void esp_netif_attach_wifi_station_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* esp_netif, int esp_netif_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE));
  CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_attach_wifi_station_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_attach_wifi_station_CallInstance, cmock_guts_index);
  Mock.esp_netif_attach_wifi_station_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_attach_wifi_station(cmock_call_instance, esp_netif, esp_netif_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_attach_wifi_station_CMockReturnMemThruPtr_esp_netif(UNITY_LINE_TYPE cmock_line, esp_netif_t* esp_netif, size_t cmock_size)
{
  CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_attach_wifi_station_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 1;
  cmock_call_instance->ReturnThruPtr_esp_netif_Val = esp_netif;
  cmock_call_instance->ReturnThruPtr_esp_netif_Size = cmock_size;
}

void esp_netif_attach_wifi_station_CMockIgnoreArg_esp_netif(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_station_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_attach_wifi_station_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_esp_netif = 1;
}

esp_err_t esp_netif_attach_wifi_ap(esp_netif_t* esp_netif)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_attach_wifi_ap);
  cmock_call_instance = (CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_attach_wifi_ap_CallInstance);
  Mock.esp_netif_attach_wifi_ap_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_attach_wifi_ap_CallInstance);
  if (Mock.esp_netif_attach_wifi_ap_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_netif_attach_wifi_ap_FinalReturn;
    memcpy((void*)(&Mock.esp_netif_attach_wifi_ap_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_netif_attach_wifi_ap_CallbackBool &&
      Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer(esp_netif, Mock.esp_netif_attach_wifi_ap_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_esp_netif)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_attach_wifi_ap,CMockString_esp_netif);
    if (cmock_call_instance->Expected_esp_netif == NULL)
      { UNITY_TEST_ASSERT_NULL(esp_netif, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_esp_netif), (void*)(esp_netif), sizeof(esp_netif_t), cmock_call_instance->Expected_esp_netif_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer(esp_netif, Mock.esp_netif_attach_wifi_ap_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_esp_netif_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(esp_netif, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)esp_netif, (void*)cmock_call_instance->ReturnThruPtr_esp_netif_Val,
      cmock_call_instance->ReturnThruPtr_esp_netif_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_netif_attach_wifi_ap(CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance, esp_netif_t* esp_netif, int esp_netif_Depth);
void CMockExpectParameters_esp_netif_attach_wifi_ap(CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance, esp_netif_t* esp_netif, int esp_netif_Depth)
{
  cmock_call_instance->Expected_esp_netif = esp_netif;
  cmock_call_instance->Expected_esp_netif_Depth = esp_netif_Depth;
  cmock_call_instance->IgnoreArg_esp_netif = 0;
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 0;
}

void esp_netif_attach_wifi_ap_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE));
  CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_attach_wifi_ap_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_attach_wifi_ap_CallInstance, cmock_guts_index);
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)1;
}

void esp_netif_attach_wifi_ap_CMockStopIgnore(void)
{
  if(Mock.esp_netif_attach_wifi_ap_IgnoreBool)
    Mock.esp_netif_attach_wifi_ap_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_attach_wifi_ap_CallInstance);
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)0;
}

void esp_netif_attach_wifi_ap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* esp_netif, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE));
  CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_attach_wifi_ap_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_attach_wifi_ap_CallInstance, cmock_guts_index);
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_attach_wifi_ap(cmock_call_instance, esp_netif, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_netif_attach_wifi_ap_AddCallback(CMOCK_esp_netif_attach_wifi_ap_CALLBACK Callback)
{
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)0;
  Mock.esp_netif_attach_wifi_ap_CallbackBool = (char)1;
  Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer = Callback;
}

void esp_netif_attach_wifi_ap_Stub(CMOCK_esp_netif_attach_wifi_ap_CALLBACK Callback)
{
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)0;
  Mock.esp_netif_attach_wifi_ap_CallbackBool = (char)0;
  Mock.esp_netif_attach_wifi_ap_CallbackFunctionPointer = Callback;
}

void esp_netif_attach_wifi_ap_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* esp_netif, int esp_netif_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE));
  CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_attach_wifi_ap_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_attach_wifi_ap_CallInstance, cmock_guts_index);
  Mock.esp_netif_attach_wifi_ap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_attach_wifi_ap(cmock_call_instance, esp_netif, esp_netif_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_attach_wifi_ap_CMockReturnMemThruPtr_esp_netif(UNITY_LINE_TYPE cmock_line, esp_netif_t* esp_netif, size_t cmock_size)
{
  CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_attach_wifi_ap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 1;
  cmock_call_instance->ReturnThruPtr_esp_netif_Val = esp_netif;
  cmock_call_instance->ReturnThruPtr_esp_netif_Size = cmock_size;
}

void esp_netif_attach_wifi_ap_CMockIgnoreArg_esp_netif(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_attach_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_attach_wifi_ap_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_esp_netif = 1;
}

esp_err_t esp_wifi_set_default_wifi_sta_handlers(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_wifi_set_default_wifi_sta_handlers);
  cmock_call_instance = (CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance);
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance = CMock_Guts_MemNext(Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance);
  if (Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_wifi_set_default_wifi_sta_handlers_FinalReturn;
    memcpy((void*)(&Mock.esp_wifi_set_default_wifi_sta_handlers_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackBool &&
      Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer(Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer(Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_wifi_set_default_wifi_sta_handlers_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool = (char)1;
}

void esp_wifi_set_default_wifi_sta_handlers_CMockStopIgnore(void)
{
  if(Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool)
    Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance = CMock_Guts_MemNext(Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance);
  Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool = (char)0;
}

void esp_wifi_set_default_wifi_sta_handlers_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_set_default_wifi_sta_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_wifi_set_default_wifi_sta_handlers_AddCallback(CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALLBACK Callback)
{
  Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool = (char)0;
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackBool = (char)1;
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer = Callback;
}

void esp_wifi_set_default_wifi_sta_handlers_Stub(CMOCK_esp_wifi_set_default_wifi_sta_handlers_CALLBACK Callback)
{
  Mock.esp_wifi_set_default_wifi_sta_handlers_IgnoreBool = (char)0;
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackBool = (char)0;
  Mock.esp_wifi_set_default_wifi_sta_handlers_CallbackFunctionPointer = Callback;
}

esp_err_t esp_wifi_set_default_wifi_ap_handlers(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_wifi_set_default_wifi_ap_handlers);
  cmock_call_instance = (CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance);
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance = CMock_Guts_MemNext(Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance);
  if (Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_wifi_set_default_wifi_ap_handlers_FinalReturn;
    memcpy((void*)(&Mock.esp_wifi_set_default_wifi_ap_handlers_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackBool &&
      Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer(Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer(Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_wifi_set_default_wifi_ap_handlers_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool = (char)1;
}

void esp_wifi_set_default_wifi_ap_handlers_CMockStopIgnore(void)
{
  if(Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool)
    Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance = CMock_Guts_MemNext(Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance);
  Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool = (char)0;
}

void esp_wifi_set_default_wifi_ap_handlers_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_set_default_wifi_ap_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_wifi_set_default_wifi_ap_handlers_AddCallback(CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALLBACK Callback)
{
  Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool = (char)0;
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackBool = (char)1;
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer = Callback;
}

void esp_wifi_set_default_wifi_ap_handlers_Stub(CMOCK_esp_wifi_set_default_wifi_ap_handlers_CALLBACK Callback)
{
  Mock.esp_wifi_set_default_wifi_ap_handlers_IgnoreBool = (char)0;
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackBool = (char)0;
  Mock.esp_wifi_set_default_wifi_ap_handlers_CallbackFunctionPointer = Callback;
}

esp_err_t esp_wifi_clear_default_wifi_driver_and_handlers(void* esp_netif)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_wifi_clear_default_wifi_driver_and_handlers);
  cmock_call_instance = (CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance);
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance = CMock_Guts_MemNext(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance);
  if (Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_wifi_clear_default_wifi_driver_and_handlers_FinalReturn;
    memcpy((void*)(&Mock.esp_wifi_clear_default_wifi_driver_and_handlers_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackBool &&
      Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer(esp_netif, Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_esp_netif)
  {
    UNITY_SET_DETAILS(CMockString_esp_wifi_clear_default_wifi_driver_and_handlers,CMockString_esp_netif);
    if (cmock_call_instance->Expected_esp_netif == NULL)
      { UNITY_TEST_ASSERT_NULL(esp_netif, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_esp_netif, esp_netif, cmock_call_instance->Expected_esp_netif_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer(esp_netif, Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_esp_netif_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(esp_netif, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)esp_netif, (void*)cmock_call_instance->ReturnThruPtr_esp_netif_Val,
      cmock_call_instance->ReturnThruPtr_esp_netif_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_wifi_clear_default_wifi_driver_and_handlers(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance, void* esp_netif, int esp_netif_Depth);
void CMockExpectParameters_esp_wifi_clear_default_wifi_driver_and_handlers(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance, void* esp_netif, int esp_netif_Depth)
{
  cmock_call_instance->Expected_esp_netif = esp_netif;
  cmock_call_instance->Expected_esp_netif_Depth = esp_netif_Depth;
  cmock_call_instance->IgnoreArg_esp_netif = 0;
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 0;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)1;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_CMockStopIgnore(void)
{
  if(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool)
    Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance = CMock_Guts_MemNext(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance);
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)0;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* esp_netif, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_wifi_clear_default_wifi_driver_and_handlers(cmock_call_instance, esp_netif, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_wifi_clear_default_wifi_driver_and_handlers_AddCallback(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALLBACK Callback)
{
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)0;
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackBool = (char)1;
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer = Callback;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_Stub(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALLBACK Callback)
{
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)0;
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackBool = (char)0;
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallbackFunctionPointer = Callback;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, void* esp_netif, int esp_netif_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE));
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance = CMock_Guts_MemChain(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance, cmock_guts_index);
  Mock.esp_wifi_clear_default_wifi_driver_and_handlers_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_wifi_clear_default_wifi_driver_and_handlers(cmock_call_instance, esp_netif, esp_netif_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_CMockReturnMemThruPtr_esp_netif(UNITY_LINE_TYPE cmock_line, void* esp_netif, size_t cmock_size)
{
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 1;
  cmock_call_instance->ReturnThruPtr_esp_netif_Val = esp_netif;
  cmock_call_instance->ReturnThruPtr_esp_netif_Size = cmock_size;
}

void esp_wifi_clear_default_wifi_driver_and_handlers_CMockIgnoreArg_esp_netif(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_wifi_clear_default_wifi_driver_and_handlers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_wifi_clear_default_wifi_driver_and_handlers_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_esp_netif = 1;
}

esp_netif_t* esp_netif_create_default_wifi_ap(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_create_default_wifi_ap);
  cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_create_default_wifi_ap_CallInstance);
  Mock.esp_netif_create_default_wifi_ap_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_default_wifi_ap_CallInstance);
  if (Mock.esp_netif_create_default_wifi_ap_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_netif_create_default_wifi_ap_FinalReturn;
    Mock.esp_netif_create_default_wifi_ap_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_netif_create_default_wifi_ap_CallbackBool &&
      Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer != NULL)
  {
    esp_netif_t* cmock_cb_ret = Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer(Mock.esp_netif_create_default_wifi_ap_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer(Mock.esp_netif_create_default_wifi_ap_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_netif_create_default_wifi_ap_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_ap_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_ap_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_ap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_netif_create_default_wifi_ap_IgnoreBool = (char)1;
}

void esp_netif_create_default_wifi_ap_CMockStopIgnore(void)
{
  if(Mock.esp_netif_create_default_wifi_ap_IgnoreBool)
    Mock.esp_netif_create_default_wifi_ap_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_default_wifi_ap_CallInstance);
  Mock.esp_netif_create_default_wifi_ap_IgnoreBool = (char)0;
}

void esp_netif_create_default_wifi_ap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_ap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_ap_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_ap_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_ap_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_create_default_wifi_ap_AddCallback(CMOCK_esp_netif_create_default_wifi_ap_CALLBACK Callback)
{
  Mock.esp_netif_create_default_wifi_ap_IgnoreBool = (char)0;
  Mock.esp_netif_create_default_wifi_ap_CallbackBool = (char)1;
  Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer = Callback;
}

void esp_netif_create_default_wifi_ap_Stub(CMOCK_esp_netif_create_default_wifi_ap_CALLBACK Callback)
{
  Mock.esp_netif_create_default_wifi_ap_IgnoreBool = (char)0;
  Mock.esp_netif_create_default_wifi_ap_CallbackBool = (char)0;
  Mock.esp_netif_create_default_wifi_ap_CallbackFunctionPointer = Callback;
}

esp_netif_t* esp_netif_create_default_wifi_sta(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_create_default_wifi_sta);
  cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_create_default_wifi_sta_CallInstance);
  Mock.esp_netif_create_default_wifi_sta_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_default_wifi_sta_CallInstance);
  if (Mock.esp_netif_create_default_wifi_sta_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_netif_create_default_wifi_sta_FinalReturn;
    Mock.esp_netif_create_default_wifi_sta_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_netif_create_default_wifi_sta_CallbackBool &&
      Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer != NULL)
  {
    esp_netif_t* cmock_cb_ret = Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer(Mock.esp_netif_create_default_wifi_sta_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer(Mock.esp_netif_create_default_wifi_sta_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void esp_netif_create_default_wifi_sta_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_sta_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_sta_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_sta_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_netif_create_default_wifi_sta_IgnoreBool = (char)1;
}

void esp_netif_create_default_wifi_sta_CMockStopIgnore(void)
{
  if(Mock.esp_netif_create_default_wifi_sta_IgnoreBool)
    Mock.esp_netif_create_default_wifi_sta_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_default_wifi_sta_CallInstance);
  Mock.esp_netif_create_default_wifi_sta_IgnoreBool = (char)0;
}

void esp_netif_create_default_wifi_sta_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_sta_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_sta_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_sta_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_sta_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_create_default_wifi_sta_AddCallback(CMOCK_esp_netif_create_default_wifi_sta_CALLBACK Callback)
{
  Mock.esp_netif_create_default_wifi_sta_IgnoreBool = (char)0;
  Mock.esp_netif_create_default_wifi_sta_CallbackBool = (char)1;
  Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer = Callback;
}

void esp_netif_create_default_wifi_sta_Stub(CMOCK_esp_netif_create_default_wifi_sta_CALLBACK Callback)
{
  Mock.esp_netif_create_default_wifi_sta_IgnoreBool = (char)0;
  Mock.esp_netif_create_default_wifi_sta_CallbackBool = (char)0;
  Mock.esp_netif_create_default_wifi_sta_CallbackFunctionPointer = Callback;
}

void esp_netif_destroy_default_wifi(void* esp_netif)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_destroy_default_wifi);
  cmock_call_instance = (CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_destroy_default_wifi_CallInstance);
  Mock.esp_netif_destroy_default_wifi_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_destroy_default_wifi_CallInstance);
  if (Mock.esp_netif_destroy_default_wifi_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.esp_netif_destroy_default_wifi_CallbackBool &&
      Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer != NULL)
  {
    Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer(esp_netif, Mock.esp_netif_destroy_default_wifi_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_esp_netif)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_destroy_default_wifi,CMockString_esp_netif);
    if (cmock_call_instance->Expected_esp_netif == NULL)
      { UNITY_TEST_ASSERT_NULL(esp_netif, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_esp_netif, esp_netif, cmock_call_instance->Expected_esp_netif_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer != NULL)
  {
    Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer(esp_netif, Mock.esp_netif_destroy_default_wifi_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_esp_netif_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(esp_netif, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)esp_netif, (void*)cmock_call_instance->ReturnThruPtr_esp_netif_Val,
      cmock_call_instance->ReturnThruPtr_esp_netif_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_esp_netif_destroy_default_wifi(CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance, void* esp_netif, int esp_netif_Depth);
void CMockExpectParameters_esp_netif_destroy_default_wifi(CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance, void* esp_netif, int esp_netif_Depth)
{
  cmock_call_instance->Expected_esp_netif = esp_netif;
  cmock_call_instance->Expected_esp_netif_Depth = esp_netif_Depth;
  cmock_call_instance->IgnoreArg_esp_netif = 0;
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 0;
}

void esp_netif_destroy_default_wifi_CMockIgnore(void)
{
  Mock.esp_netif_destroy_default_wifi_IgnoreBool = (char)1;
}

void esp_netif_destroy_default_wifi_CMockStopIgnore(void)
{
  Mock.esp_netif_destroy_default_wifi_IgnoreBool = (char)0;
}

void esp_netif_destroy_default_wifi_CMockExpect(UNITY_LINE_TYPE cmock_line, void* esp_netif)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE));
  CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_destroy_default_wifi_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_destroy_default_wifi_CallInstance, cmock_guts_index);
  Mock.esp_netif_destroy_default_wifi_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_destroy_default_wifi(cmock_call_instance, esp_netif, 1);
}

void esp_netif_destroy_default_wifi_AddCallback(CMOCK_esp_netif_destroy_default_wifi_CALLBACK Callback)
{
  Mock.esp_netif_destroy_default_wifi_IgnoreBool = (char)0;
  Mock.esp_netif_destroy_default_wifi_CallbackBool = (char)1;
  Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer = Callback;
}

void esp_netif_destroy_default_wifi_Stub(CMOCK_esp_netif_destroy_default_wifi_CALLBACK Callback)
{
  Mock.esp_netif_destroy_default_wifi_IgnoreBool = (char)0;
  Mock.esp_netif_destroy_default_wifi_CallbackBool = (char)0;
  Mock.esp_netif_destroy_default_wifi_CallbackFunctionPointer = Callback;
}

void esp_netif_destroy_default_wifi_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, void* esp_netif, int esp_netif_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE));
  CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_destroy_default_wifi_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_destroy_default_wifi_CallInstance, cmock_guts_index);
  Mock.esp_netif_destroy_default_wifi_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_destroy_default_wifi(cmock_call_instance, esp_netif, esp_netif_Depth);
}

void esp_netif_destroy_default_wifi_CMockReturnMemThruPtr_esp_netif(UNITY_LINE_TYPE cmock_line, void* esp_netif, size_t cmock_size)
{
  CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_destroy_default_wifi_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_esp_netif_Used = 1;
  cmock_call_instance->ReturnThruPtr_esp_netif_Val = esp_netif;
  cmock_call_instance->ReturnThruPtr_esp_netif_Size = cmock_size;
}

void esp_netif_destroy_default_wifi_CMockIgnoreArg_esp_netif(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_destroy_default_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_destroy_default_wifi_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_esp_netif = 1;
}

esp_netif_t* esp_netif_create_wifi(wifi_interface_t wifi_if, esp_netif_inherent_config_t* esp_netif_config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_create_wifi);
  cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_create_wifi_CallInstance);
  Mock.esp_netif_create_wifi_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_wifi_CallInstance);
  if (Mock.esp_netif_create_wifi_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_netif_create_wifi_FinalReturn;
    Mock.esp_netif_create_wifi_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_netif_create_wifi_CallbackBool &&
      Mock.esp_netif_create_wifi_CallbackFunctionPointer != NULL)
  {
    esp_netif_t* cmock_cb_ret = Mock.esp_netif_create_wifi_CallbackFunctionPointer(wifi_if, esp_netif_config, Mock.esp_netif_create_wifi_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_wifi_if)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_create_wifi,CMockString_wifi_if);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_wifi_if), (void*)(&wifi_if), sizeof(wifi_interface_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_esp_netif_config)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_create_wifi,CMockString_esp_netif_config);
    if (cmock_call_instance->Expected_esp_netif_config == NULL)
      { UNITY_TEST_ASSERT_NULL(esp_netif_config, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_esp_netif_config), (void*)(esp_netif_config), sizeof(esp_netif_inherent_config_t), cmock_call_instance->Expected_esp_netif_config_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_netif_create_wifi_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_netif_create_wifi_CallbackFunctionPointer(wifi_if, esp_netif_config, Mock.esp_netif_create_wifi_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_esp_netif_config_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(esp_netif_config, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)esp_netif_config, (void*)cmock_call_instance->ReturnThruPtr_esp_netif_config_Val,
      cmock_call_instance->ReturnThruPtr_esp_netif_config_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_netif_create_wifi(CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance, wifi_interface_t wifi_if, esp_netif_inherent_config_t* esp_netif_config, int esp_netif_config_Depth);
void CMockExpectParameters_esp_netif_create_wifi(CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance, wifi_interface_t wifi_if, esp_netif_inherent_config_t* esp_netif_config, int esp_netif_config_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_wifi_if), (void*)(&wifi_if),
         sizeof(wifi_interface_t[sizeof(wifi_if) == sizeof(wifi_interface_t) ? 1 : -1])); /* add wifi_interface_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_wifi_if = 0;
  cmock_call_instance->Expected_esp_netif_config = esp_netif_config;
  cmock_call_instance->Expected_esp_netif_config_Depth = esp_netif_config_Depth;
  cmock_call_instance->IgnoreArg_esp_netif_config = 0;
  cmock_call_instance->ReturnThruPtr_esp_netif_config_Used = 0;
}

void esp_netif_create_wifi_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_wifi_CALL_INSTANCE));
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_wifi_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_wifi_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_wifi_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_netif_create_wifi_IgnoreBool = (char)1;
}

void esp_netif_create_wifi_CMockStopIgnore(void)
{
  if(Mock.esp_netif_create_wifi_IgnoreBool)
    Mock.esp_netif_create_wifi_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_wifi_CallInstance);
  Mock.esp_netif_create_wifi_IgnoreBool = (char)0;
}

void esp_netif_create_wifi_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, wifi_interface_t wifi_if, esp_netif_inherent_config_t* esp_netif_config, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_wifi_CALL_INSTANCE));
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_wifi_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_wifi_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_wifi_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_create_wifi(cmock_call_instance, wifi_if, esp_netif_config, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_create_wifi_AddCallback(CMOCK_esp_netif_create_wifi_CALLBACK Callback)
{
  Mock.esp_netif_create_wifi_IgnoreBool = (char)0;
  Mock.esp_netif_create_wifi_CallbackBool = (char)1;
  Mock.esp_netif_create_wifi_CallbackFunctionPointer = Callback;
}

void esp_netif_create_wifi_Stub(CMOCK_esp_netif_create_wifi_CALLBACK Callback)
{
  Mock.esp_netif_create_wifi_IgnoreBool = (char)0;
  Mock.esp_netif_create_wifi_CallbackBool = (char)0;
  Mock.esp_netif_create_wifi_CallbackFunctionPointer = Callback;
}

void esp_netif_create_wifi_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, wifi_interface_t wifi_if, esp_netif_inherent_config_t* esp_netif_config, int esp_netif_config_Depth, esp_netif_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_wifi_CALL_INSTANCE));
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_wifi_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_wifi_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_wifi_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_create_wifi(cmock_call_instance, wifi_if, esp_netif_config, esp_netif_config_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_create_wifi_CMockReturnMemThruPtr_esp_netif_config(UNITY_LINE_TYPE cmock_line, esp_netif_inherent_config_t* esp_netif_config, size_t cmock_size)
{
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_wifi_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_esp_netif_config_Used = 1;
  cmock_call_instance->ReturnThruPtr_esp_netif_config_Val = esp_netif_config;
  cmock_call_instance->ReturnThruPtr_esp_netif_config_Size = cmock_size;
}

void esp_netif_create_wifi_CMockIgnoreArg_wifi_if(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_wifi_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_wifi_if = 1;
}

void esp_netif_create_wifi_CMockIgnoreArg_esp_netif_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_create_wifi_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_wifi_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_wifi_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_esp_netif_config = 1;
}

esp_err_t esp_netif_create_default_wifi_mesh_netifs(esp_netif_t** p_netif_sta, esp_netif_t** p_netif_ap)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_netif_create_default_wifi_mesh_netifs);
  cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance);
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance);
  if (Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_netif_create_default_wifi_mesh_netifs_FinalReturn;
    memcpy((void*)(&Mock.esp_netif_create_default_wifi_mesh_netifs_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackBool &&
      Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer(p_netif_sta, p_netif_ap, Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_p_netif_sta)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_create_default_wifi_mesh_netifs,CMockString_p_netif_sta);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_p_netif_sta, p_netif_sta, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_p_netif_ap)
  {
    UNITY_SET_DETAILS(CMockString_esp_netif_create_default_wifi_mesh_netifs,CMockString_p_netif_ap);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_p_netif_ap, p_netif_ap, cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer(p_netif_sta, p_netif_ap, Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_p_netif_sta_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(p_netif_sta, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)p_netif_sta, (void*)cmock_call_instance->ReturnThruPtr_p_netif_sta_Val,
      cmock_call_instance->ReturnThruPtr_p_netif_sta_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_p_netif_ap_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(p_netif_ap, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)p_netif_ap, (void*)cmock_call_instance->ReturnThruPtr_p_netif_ap_Val,
      cmock_call_instance->ReturnThruPtr_p_netif_ap_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_netif_create_default_wifi_mesh_netifs(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance, esp_netif_t** p_netif_sta, int p_netif_sta_Depth, esp_netif_t** p_netif_ap, int p_netif_ap_Depth);
void CMockExpectParameters_esp_netif_create_default_wifi_mesh_netifs(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance, esp_netif_t** p_netif_sta, int p_netif_sta_Depth, esp_netif_t** p_netif_ap, int p_netif_ap_Depth)
{
  cmock_call_instance->Expected_p_netif_sta = p_netif_sta;
  cmock_call_instance->Expected_p_netif_sta_Depth = p_netif_sta_Depth;
  cmock_call_instance->IgnoreArg_p_netif_sta = 0;
  cmock_call_instance->ReturnThruPtr_p_netif_sta_Used = 0;
  cmock_call_instance->Expected_p_netif_ap = p_netif_ap;
  cmock_call_instance->Expected_p_netif_ap_Depth = p_netif_ap_Depth;
  cmock_call_instance->IgnoreArg_p_netif_ap = 0;
  cmock_call_instance->ReturnThruPtr_p_netif_ap_Used = 0;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)1;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockStopIgnore(void)
{
  if(Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool)
    Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance = CMock_Guts_MemNext(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance);
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)0;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t** p_netif_sta, esp_netif_t** p_netif_ap, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_create_default_wifi_mesh_netifs(cmock_call_instance, p_netif_sta, 1, p_netif_ap, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_netif_create_default_wifi_mesh_netifs_AddCallback(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALLBACK Callback)
{
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)0;
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackBool = (char)1;
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer = Callback;
}

void esp_netif_create_default_wifi_mesh_netifs_Stub(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALLBACK Callback)
{
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)0;
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackBool = (char)0;
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallbackFunctionPointer = Callback;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, esp_netif_t** p_netif_sta, int p_netif_sta_Depth, esp_netif_t** p_netif_ap, int p_netif_ap_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE));
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance = CMock_Guts_MemChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance, cmock_guts_index);
  Mock.esp_netif_create_default_wifi_mesh_netifs_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_netif_create_default_wifi_mesh_netifs(cmock_call_instance, p_netif_sta, p_netif_sta_Depth, p_netif_ap, p_netif_ap_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockReturnMemThruPtr_p_netif_sta(UNITY_LINE_TYPE cmock_line, esp_netif_t** p_netif_sta, size_t cmock_size)
{
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_p_netif_sta_Used = 1;
  cmock_call_instance->ReturnThruPtr_p_netif_sta_Val = p_netif_sta;
  cmock_call_instance->ReturnThruPtr_p_netif_sta_Size = cmock_size;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockReturnMemThruPtr_p_netif_ap(UNITY_LINE_TYPE cmock_line, esp_netif_t** p_netif_ap, size_t cmock_size)
{
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_p_netif_ap_Used = 1;
  cmock_call_instance->ReturnThruPtr_p_netif_ap_Val = p_netif_ap;
  cmock_call_instance->ReturnThruPtr_p_netif_ap_Size = cmock_size;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockIgnoreArg_p_netif_sta(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_p_netif_sta = 1;
}

void esp_netif_create_default_wifi_mesh_netifs_CMockIgnoreArg_p_netif_ap(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_netif_create_default_wifi_mesh_netifs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_netif_create_default_wifi_mesh_netifs_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_p_netif_ap = 1;
}

