/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_esp_mac.h"

static const char* CMockString_esp_base_mac_addr_get = "esp_base_mac_addr_get";
static const char* CMockString_esp_base_mac_addr_set = "esp_base_mac_addr_set";
static const char* CMockString_esp_derive_local_mac = "esp_derive_local_mac";
static const char* CMockString_esp_efuse_mac_get_custom = "esp_efuse_mac_get_custom";
static const char* CMockString_esp_efuse_mac_get_default = "esp_efuse_mac_get_default";
static const char* CMockString_esp_read_mac = "esp_read_mac";
static const char* CMockString_local_mac = "local_mac";
static const char* CMockString_mac = "mac";
static const char* CMockString_type = "type";
static const char* CMockString_universal_mac = "universal_mac";

typedef struct _CMOCK_esp_base_mac_addr_set_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  const uint8_t* Expected_mac;
  int Expected_mac_Depth;
  char IgnoreArg_mac;

} CMOCK_esp_base_mac_addr_set_CALL_INSTANCE;

typedef struct _CMOCK_esp_base_mac_addr_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint8_t* Expected_mac;
  int Expected_mac_Depth;
  char ReturnThruPtr_mac_Used;
  uint8_t* ReturnThruPtr_mac_Val;
  size_t ReturnThruPtr_mac_Size;
  char IgnoreArg_mac;

} CMOCK_esp_base_mac_addr_get_CALL_INSTANCE;

typedef struct _CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint8_t* Expected_mac;
  int Expected_mac_Depth;
  char ReturnThruPtr_mac_Used;
  uint8_t* ReturnThruPtr_mac_Val;
  size_t ReturnThruPtr_mac_Size;
  char IgnoreArg_mac;

} CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE;

typedef struct _CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint8_t* Expected_mac;
  int Expected_mac_Depth;
  char ReturnThruPtr_mac_Used;
  uint8_t* ReturnThruPtr_mac_Val;
  size_t ReturnThruPtr_mac_Size;
  char IgnoreArg_mac;

} CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE;

typedef struct _CMOCK_esp_read_mac_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint8_t* Expected_mac;
  esp_mac_type_t Expected_type;
  int Expected_mac_Depth;
  char ReturnThruPtr_mac_Used;
  uint8_t* ReturnThruPtr_mac_Val;
  size_t ReturnThruPtr_mac_Size;
  char IgnoreArg_mac;
  char IgnoreArg_type;

} CMOCK_esp_read_mac_CALL_INSTANCE;

typedef struct _CMOCK_esp_derive_local_mac_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint8_t* Expected_local_mac;
  const uint8_t* Expected_universal_mac;
  int Expected_local_mac_Depth;
  int Expected_universal_mac_Depth;
  char ReturnThruPtr_local_mac_Used;
  uint8_t* ReturnThruPtr_local_mac_Val;
  size_t ReturnThruPtr_local_mac_Size;
  char IgnoreArg_local_mac;
  char IgnoreArg_universal_mac;

} CMOCK_esp_derive_local_mac_CALL_INSTANCE;

static struct mock_esp_macInstance
{
  char esp_base_mac_addr_set_IgnoreBool;
  esp_err_t esp_base_mac_addr_set_FinalReturn;
  char esp_base_mac_addr_set_CallbackBool;
  CMOCK_esp_base_mac_addr_set_CALLBACK esp_base_mac_addr_set_CallbackFunctionPointer;
  int esp_base_mac_addr_set_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_base_mac_addr_set_CallInstance;
  char esp_base_mac_addr_get_IgnoreBool;
  esp_err_t esp_base_mac_addr_get_FinalReturn;
  char esp_base_mac_addr_get_CallbackBool;
  CMOCK_esp_base_mac_addr_get_CALLBACK esp_base_mac_addr_get_CallbackFunctionPointer;
  int esp_base_mac_addr_get_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_base_mac_addr_get_CallInstance;
  char esp_efuse_mac_get_custom_IgnoreBool;
  esp_err_t esp_efuse_mac_get_custom_FinalReturn;
  char esp_efuse_mac_get_custom_CallbackBool;
  CMOCK_esp_efuse_mac_get_custom_CALLBACK esp_efuse_mac_get_custom_CallbackFunctionPointer;
  int esp_efuse_mac_get_custom_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_efuse_mac_get_custom_CallInstance;
  char esp_efuse_mac_get_default_IgnoreBool;
  esp_err_t esp_efuse_mac_get_default_FinalReturn;
  char esp_efuse_mac_get_default_CallbackBool;
  CMOCK_esp_efuse_mac_get_default_CALLBACK esp_efuse_mac_get_default_CallbackFunctionPointer;
  int esp_efuse_mac_get_default_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_efuse_mac_get_default_CallInstance;
  char esp_read_mac_IgnoreBool;
  esp_err_t esp_read_mac_FinalReturn;
  char esp_read_mac_CallbackBool;
  CMOCK_esp_read_mac_CALLBACK esp_read_mac_CallbackFunctionPointer;
  int esp_read_mac_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_read_mac_CallInstance;
  char esp_derive_local_mac_IgnoreBool;
  esp_err_t esp_derive_local_mac_FinalReturn;
  char esp_derive_local_mac_CallbackBool;
  CMOCK_esp_derive_local_mac_CALLBACK esp_derive_local_mac_CallbackFunctionPointer;
  int esp_derive_local_mac_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE esp_derive_local_mac_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_esp_mac_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.esp_base_mac_addr_set_CallInstance;
  if (Mock.esp_base_mac_addr_set_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_base_mac_addr_set);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_base_mac_addr_set_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_base_mac_addr_get_CallInstance;
  if (Mock.esp_base_mac_addr_get_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_base_mac_addr_get);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_base_mac_addr_get_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_efuse_mac_get_custom_CallInstance;
  if (Mock.esp_efuse_mac_get_custom_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_efuse_mac_get_custom);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_efuse_mac_get_default_CallInstance;
  if (Mock.esp_efuse_mac_get_default_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_efuse_mac_get_default);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_efuse_mac_get_default_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_read_mac_CallInstance;
  if (Mock.esp_read_mac_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_read_mac);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_read_mac_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.esp_derive_local_mac_CallInstance;
  if (Mock.esp_derive_local_mac_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_derive_local_mac);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.esp_derive_local_mac_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_esp_mac_Init(void)
{
  mock_esp_mac_Destroy();
}

void mock_esp_mac_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t esp_base_mac_addr_set(const uint8_t* mac)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_base_mac_addr_set);
  cmock_call_instance = (CMOCK_esp_base_mac_addr_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_base_mac_addr_set_CallInstance);
  Mock.esp_base_mac_addr_set_CallInstance = CMock_Guts_MemNext(Mock.esp_base_mac_addr_set_CallInstance);
  if (Mock.esp_base_mac_addr_set_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_base_mac_addr_set_FinalReturn;
    memcpy((void*)(&Mock.esp_base_mac_addr_set_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_base_mac_addr_set_CallbackBool &&
      Mock.esp_base_mac_addr_set_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_base_mac_addr_set_CallbackFunctionPointer(mac, Mock.esp_base_mac_addr_set_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_base_mac_addr_set,CMockString_mac);
    if (cmock_call_instance->Expected_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_mac, mac, cmock_call_instance->Expected_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_base_mac_addr_set_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_base_mac_addr_set_CallbackFunctionPointer(mac, Mock.esp_base_mac_addr_set_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_base_mac_addr_set(CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance, const uint8_t* mac, int mac_Depth);
void CMockExpectParameters_esp_base_mac_addr_set(CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance, const uint8_t* mac, int mac_Depth)
{
  cmock_call_instance->Expected_mac = mac;
  cmock_call_instance->Expected_mac_Depth = mac_Depth;
  cmock_call_instance->IgnoreArg_mac = 0;
}

void esp_base_mac_addr_set_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_base_mac_addr_set_CALL_INSTANCE));
  CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_base_mac_addr_set_CallInstance = CMock_Guts_MemChain(Mock.esp_base_mac_addr_set_CallInstance, cmock_guts_index);
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)1;
}

void esp_base_mac_addr_set_CMockStopIgnore(void)
{
  if(Mock.esp_base_mac_addr_set_IgnoreBool)
    Mock.esp_base_mac_addr_set_CallInstance = CMock_Guts_MemNext(Mock.esp_base_mac_addr_set_CallInstance);
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)0;
}

void esp_base_mac_addr_set_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* mac, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_base_mac_addr_set_CALL_INSTANCE));
  CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_base_mac_addr_set_CallInstance = CMock_Guts_MemChain(Mock.esp_base_mac_addr_set_CallInstance, cmock_guts_index);
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_base_mac_addr_set(cmock_call_instance, mac, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_base_mac_addr_set_AddCallback(CMOCK_esp_base_mac_addr_set_CALLBACK Callback)
{
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)0;
  Mock.esp_base_mac_addr_set_CallbackBool = (char)1;
  Mock.esp_base_mac_addr_set_CallbackFunctionPointer = Callback;
}

void esp_base_mac_addr_set_Stub(CMOCK_esp_base_mac_addr_set_CALLBACK Callback)
{
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)0;
  Mock.esp_base_mac_addr_set_CallbackBool = (char)0;
  Mock.esp_base_mac_addr_set_CallbackFunctionPointer = Callback;
}

void esp_base_mac_addr_set_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* mac, int mac_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_base_mac_addr_set_CALL_INSTANCE));
  CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_base_mac_addr_set_CallInstance = CMock_Guts_MemChain(Mock.esp_base_mac_addr_set_CallInstance, cmock_guts_index);
  Mock.esp_base_mac_addr_set_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_base_mac_addr_set(cmock_call_instance, mac, mac_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_base_mac_addr_set_CMockIgnoreArg_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_base_mac_addr_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_base_mac_addr_set_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mac = 1;
}

esp_err_t esp_base_mac_addr_get(uint8_t* mac)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_base_mac_addr_get);
  cmock_call_instance = (CMOCK_esp_base_mac_addr_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_base_mac_addr_get_CallInstance);
  Mock.esp_base_mac_addr_get_CallInstance = CMock_Guts_MemNext(Mock.esp_base_mac_addr_get_CallInstance);
  if (Mock.esp_base_mac_addr_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_base_mac_addr_get_FinalReturn;
    memcpy((void*)(&Mock.esp_base_mac_addr_get_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_base_mac_addr_get_CallbackBool &&
      Mock.esp_base_mac_addr_get_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_base_mac_addr_get_CallbackFunctionPointer(mac, Mock.esp_base_mac_addr_get_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_base_mac_addr_get,CMockString_mac);
    if (cmock_call_instance->Expected_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_mac, mac, cmock_call_instance->Expected_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_base_mac_addr_get_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_base_mac_addr_get_CallbackFunctionPointer(mac, Mock.esp_base_mac_addr_get_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_mac_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(mac, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)mac, (void*)cmock_call_instance->ReturnThruPtr_mac_Val,
      cmock_call_instance->ReturnThruPtr_mac_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_base_mac_addr_get(CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth);
void CMockExpectParameters_esp_base_mac_addr_get(CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth)
{
  cmock_call_instance->Expected_mac = mac;
  cmock_call_instance->Expected_mac_Depth = mac_Depth;
  cmock_call_instance->IgnoreArg_mac = 0;
  cmock_call_instance->ReturnThruPtr_mac_Used = 0;
}

void esp_base_mac_addr_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_base_mac_addr_get_CALL_INSTANCE));
  CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_base_mac_addr_get_CallInstance = CMock_Guts_MemChain(Mock.esp_base_mac_addr_get_CallInstance, cmock_guts_index);
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)1;
}

void esp_base_mac_addr_get_CMockStopIgnore(void)
{
  if(Mock.esp_base_mac_addr_get_IgnoreBool)
    Mock.esp_base_mac_addr_get_CallInstance = CMock_Guts_MemNext(Mock.esp_base_mac_addr_get_CallInstance);
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)0;
}

void esp_base_mac_addr_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_base_mac_addr_get_CALL_INSTANCE));
  CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_base_mac_addr_get_CallInstance = CMock_Guts_MemChain(Mock.esp_base_mac_addr_get_CallInstance, cmock_guts_index);
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_base_mac_addr_get(cmock_call_instance, mac, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_base_mac_addr_get_AddCallback(CMOCK_esp_base_mac_addr_get_CALLBACK Callback)
{
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)0;
  Mock.esp_base_mac_addr_get_CallbackBool = (char)1;
  Mock.esp_base_mac_addr_get_CallbackFunctionPointer = Callback;
}

void esp_base_mac_addr_get_Stub(CMOCK_esp_base_mac_addr_get_CALLBACK Callback)
{
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)0;
  Mock.esp_base_mac_addr_get_CallbackBool = (char)0;
  Mock.esp_base_mac_addr_get_CallbackFunctionPointer = Callback;
}

void esp_base_mac_addr_get_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, int mac_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_base_mac_addr_get_CALL_INSTANCE));
  CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_base_mac_addr_get_CallInstance = CMock_Guts_MemChain(Mock.esp_base_mac_addr_get_CallInstance, cmock_guts_index);
  Mock.esp_base_mac_addr_get_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_base_mac_addr_get(cmock_call_instance, mac, mac_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_base_mac_addr_get_CMockReturnMemThruPtr_mac(UNITY_LINE_TYPE cmock_line, uint8_t* mac, size_t cmock_size)
{
  CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_base_mac_addr_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_mac_Used = 1;
  cmock_call_instance->ReturnThruPtr_mac_Val = mac;
  cmock_call_instance->ReturnThruPtr_mac_Size = cmock_size;
}

void esp_base_mac_addr_get_CMockIgnoreArg_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_base_mac_addr_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_base_mac_addr_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_base_mac_addr_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mac = 1;
}

esp_err_t esp_efuse_mac_get_custom(uint8_t* mac)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_efuse_mac_get_custom);
  cmock_call_instance = (CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_efuse_mac_get_custom_CallInstance);
  Mock.esp_efuse_mac_get_custom_CallInstance = CMock_Guts_MemNext(Mock.esp_efuse_mac_get_custom_CallInstance);
  if (Mock.esp_efuse_mac_get_custom_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_efuse_mac_get_custom_FinalReturn;
    memcpy((void*)(&Mock.esp_efuse_mac_get_custom_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_efuse_mac_get_custom_CallbackBool &&
      Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer(mac, Mock.esp_efuse_mac_get_custom_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_efuse_mac_get_custom,CMockString_mac);
    if (cmock_call_instance->Expected_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_mac, mac, cmock_call_instance->Expected_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer(mac, Mock.esp_efuse_mac_get_custom_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_mac_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(mac, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)mac, (void*)cmock_call_instance->ReturnThruPtr_mac_Val,
      cmock_call_instance->ReturnThruPtr_mac_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_efuse_mac_get_custom(CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth);
void CMockExpectParameters_esp_efuse_mac_get_custom(CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth)
{
  cmock_call_instance->Expected_mac = mac;
  cmock_call_instance->Expected_mac_Depth = mac_Depth;
  cmock_call_instance->IgnoreArg_mac = 0;
  cmock_call_instance->ReturnThruPtr_mac_Used = 0;
}

void esp_efuse_mac_get_custom_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE));
  CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_efuse_mac_get_custom_CallInstance = CMock_Guts_MemChain(Mock.esp_efuse_mac_get_custom_CallInstance, cmock_guts_index);
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)1;
}

void esp_efuse_mac_get_custom_CMockStopIgnore(void)
{
  if(Mock.esp_efuse_mac_get_custom_IgnoreBool)
    Mock.esp_efuse_mac_get_custom_CallInstance = CMock_Guts_MemNext(Mock.esp_efuse_mac_get_custom_CallInstance);
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)0;
}

void esp_efuse_mac_get_custom_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE));
  CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_efuse_mac_get_custom_CallInstance = CMock_Guts_MemChain(Mock.esp_efuse_mac_get_custom_CallInstance, cmock_guts_index);
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_efuse_mac_get_custom(cmock_call_instance, mac, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_efuse_mac_get_custom_AddCallback(CMOCK_esp_efuse_mac_get_custom_CALLBACK Callback)
{
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)0;
  Mock.esp_efuse_mac_get_custom_CallbackBool = (char)1;
  Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer = Callback;
}

void esp_efuse_mac_get_custom_Stub(CMOCK_esp_efuse_mac_get_custom_CALLBACK Callback)
{
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)0;
  Mock.esp_efuse_mac_get_custom_CallbackBool = (char)0;
  Mock.esp_efuse_mac_get_custom_CallbackFunctionPointer = Callback;
}

void esp_efuse_mac_get_custom_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, int mac_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE));
  CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_efuse_mac_get_custom_CallInstance = CMock_Guts_MemChain(Mock.esp_efuse_mac_get_custom_CallInstance, cmock_guts_index);
  Mock.esp_efuse_mac_get_custom_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_efuse_mac_get_custom(cmock_call_instance, mac, mac_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_efuse_mac_get_custom_CMockReturnMemThruPtr_mac(UNITY_LINE_TYPE cmock_line, uint8_t* mac, size_t cmock_size)
{
  CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_efuse_mac_get_custom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_mac_Used = 1;
  cmock_call_instance->ReturnThruPtr_mac_Val = mac;
  cmock_call_instance->ReturnThruPtr_mac_Size = cmock_size;
}

void esp_efuse_mac_get_custom_CMockIgnoreArg_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_custom_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_efuse_mac_get_custom_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mac = 1;
}

esp_err_t esp_efuse_mac_get_default(uint8_t* mac)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_efuse_mac_get_default);
  cmock_call_instance = (CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_efuse_mac_get_default_CallInstance);
  Mock.esp_efuse_mac_get_default_CallInstance = CMock_Guts_MemNext(Mock.esp_efuse_mac_get_default_CallInstance);
  if (Mock.esp_efuse_mac_get_default_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_efuse_mac_get_default_FinalReturn;
    memcpy((void*)(&Mock.esp_efuse_mac_get_default_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_efuse_mac_get_default_CallbackBool &&
      Mock.esp_efuse_mac_get_default_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_efuse_mac_get_default_CallbackFunctionPointer(mac, Mock.esp_efuse_mac_get_default_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_efuse_mac_get_default,CMockString_mac);
    if (cmock_call_instance->Expected_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_mac, mac, cmock_call_instance->Expected_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_efuse_mac_get_default_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_efuse_mac_get_default_CallbackFunctionPointer(mac, Mock.esp_efuse_mac_get_default_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_mac_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(mac, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)mac, (void*)cmock_call_instance->ReturnThruPtr_mac_Val,
      cmock_call_instance->ReturnThruPtr_mac_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_efuse_mac_get_default(CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth);
void CMockExpectParameters_esp_efuse_mac_get_default(CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth)
{
  cmock_call_instance->Expected_mac = mac;
  cmock_call_instance->Expected_mac_Depth = mac_Depth;
  cmock_call_instance->IgnoreArg_mac = 0;
  cmock_call_instance->ReturnThruPtr_mac_Used = 0;
}

void esp_efuse_mac_get_default_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE));
  CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_efuse_mac_get_default_CallInstance = CMock_Guts_MemChain(Mock.esp_efuse_mac_get_default_CallInstance, cmock_guts_index);
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)1;
}

void esp_efuse_mac_get_default_CMockStopIgnore(void)
{
  if(Mock.esp_efuse_mac_get_default_IgnoreBool)
    Mock.esp_efuse_mac_get_default_CallInstance = CMock_Guts_MemNext(Mock.esp_efuse_mac_get_default_CallInstance);
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)0;
}

void esp_efuse_mac_get_default_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE));
  CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_efuse_mac_get_default_CallInstance = CMock_Guts_MemChain(Mock.esp_efuse_mac_get_default_CallInstance, cmock_guts_index);
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_efuse_mac_get_default(cmock_call_instance, mac, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_efuse_mac_get_default_AddCallback(CMOCK_esp_efuse_mac_get_default_CALLBACK Callback)
{
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)0;
  Mock.esp_efuse_mac_get_default_CallbackBool = (char)1;
  Mock.esp_efuse_mac_get_default_CallbackFunctionPointer = Callback;
}

void esp_efuse_mac_get_default_Stub(CMOCK_esp_efuse_mac_get_default_CALLBACK Callback)
{
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)0;
  Mock.esp_efuse_mac_get_default_CallbackBool = (char)0;
  Mock.esp_efuse_mac_get_default_CallbackFunctionPointer = Callback;
}

void esp_efuse_mac_get_default_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, int mac_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE));
  CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_efuse_mac_get_default_CallInstance = CMock_Guts_MemChain(Mock.esp_efuse_mac_get_default_CallInstance, cmock_guts_index);
  Mock.esp_efuse_mac_get_default_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_efuse_mac_get_default(cmock_call_instance, mac, mac_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_efuse_mac_get_default_CMockReturnMemThruPtr_mac(UNITY_LINE_TYPE cmock_line, uint8_t* mac, size_t cmock_size)
{
  CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_efuse_mac_get_default_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_mac_Used = 1;
  cmock_call_instance->ReturnThruPtr_mac_Val = mac;
  cmock_call_instance->ReturnThruPtr_mac_Size = cmock_size;
}

void esp_efuse_mac_get_default_CMockIgnoreArg_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_efuse_mac_get_default_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_efuse_mac_get_default_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mac = 1;
}

esp_err_t esp_read_mac(uint8_t* mac, esp_mac_type_t type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_read_mac);
  cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_read_mac_CallInstance);
  Mock.esp_read_mac_CallInstance = CMock_Guts_MemNext(Mock.esp_read_mac_CallInstance);
  if (Mock.esp_read_mac_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_read_mac_FinalReturn;
    memcpy((void*)(&Mock.esp_read_mac_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_read_mac_CallbackBool &&
      Mock.esp_read_mac_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_read_mac_CallbackFunctionPointer(mac, type, Mock.esp_read_mac_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_read_mac,CMockString_mac);
    if (cmock_call_instance->Expected_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_mac, mac, cmock_call_instance->Expected_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_type)
  {
    UNITY_SET_DETAILS(CMockString_esp_read_mac,CMockString_type);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(esp_mac_type_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.esp_read_mac_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_read_mac_CallbackFunctionPointer(mac, type, Mock.esp_read_mac_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_mac_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(mac, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)mac, (void*)cmock_call_instance->ReturnThruPtr_mac_Val,
      cmock_call_instance->ReturnThruPtr_mac_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_read_mac(CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth, esp_mac_type_t type);
void CMockExpectParameters_esp_read_mac(CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance, uint8_t* mac, int mac_Depth, esp_mac_type_t type)
{
  cmock_call_instance->Expected_mac = mac;
  cmock_call_instance->Expected_mac_Depth = mac_Depth;
  cmock_call_instance->IgnoreArg_mac = 0;
  cmock_call_instance->ReturnThruPtr_mac_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_type), (void*)(&type),
         sizeof(esp_mac_type_t[sizeof(type) == sizeof(esp_mac_type_t) ? 1 : -1])); /* add esp_mac_type_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_type = 0;
}

void esp_read_mac_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_read_mac_CALL_INSTANCE));
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_read_mac_CallInstance = CMock_Guts_MemChain(Mock.esp_read_mac_CallInstance, cmock_guts_index);
  Mock.esp_read_mac_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_read_mac_IgnoreBool = (char)1;
}

void esp_read_mac_CMockStopIgnore(void)
{
  if(Mock.esp_read_mac_IgnoreBool)
    Mock.esp_read_mac_CallInstance = CMock_Guts_MemNext(Mock.esp_read_mac_CallInstance);
  Mock.esp_read_mac_IgnoreBool = (char)0;
}

void esp_read_mac_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, esp_mac_type_t type, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_read_mac_CALL_INSTANCE));
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_read_mac_CallInstance = CMock_Guts_MemChain(Mock.esp_read_mac_CallInstance, cmock_guts_index);
  Mock.esp_read_mac_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_read_mac(cmock_call_instance, mac, 1, type);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_read_mac_AddCallback(CMOCK_esp_read_mac_CALLBACK Callback)
{
  Mock.esp_read_mac_IgnoreBool = (char)0;
  Mock.esp_read_mac_CallbackBool = (char)1;
  Mock.esp_read_mac_CallbackFunctionPointer = Callback;
}

void esp_read_mac_Stub(CMOCK_esp_read_mac_CALLBACK Callback)
{
  Mock.esp_read_mac_IgnoreBool = (char)0;
  Mock.esp_read_mac_CallbackBool = (char)0;
  Mock.esp_read_mac_CallbackFunctionPointer = Callback;
}

void esp_read_mac_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* mac, int mac_Depth, esp_mac_type_t type, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_read_mac_CALL_INSTANCE));
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_read_mac_CallInstance = CMock_Guts_MemChain(Mock.esp_read_mac_CallInstance, cmock_guts_index);
  Mock.esp_read_mac_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_read_mac(cmock_call_instance, mac, mac_Depth, type);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_read_mac_CMockReturnMemThruPtr_mac(UNITY_LINE_TYPE cmock_line, uint8_t* mac, size_t cmock_size)
{
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_read_mac_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_mac_Used = 1;
  cmock_call_instance->ReturnThruPtr_mac_Val = mac;
  cmock_call_instance->ReturnThruPtr_mac_Size = cmock_size;
}

void esp_read_mac_CMockIgnoreArg_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_read_mac_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mac = 1;
}

void esp_read_mac_CMockIgnoreArg_type(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_read_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_read_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_read_mac_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_type = 1;
}

esp_err_t esp_derive_local_mac(uint8_t* local_mac, const uint8_t* universal_mac)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_derive_local_mac);
  cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_derive_local_mac_CallInstance);
  Mock.esp_derive_local_mac_CallInstance = CMock_Guts_MemNext(Mock.esp_derive_local_mac_CallInstance);
  if (Mock.esp_derive_local_mac_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.esp_derive_local_mac_FinalReturn;
    memcpy((void*)(&Mock.esp_derive_local_mac_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.esp_derive_local_mac_CallbackBool &&
      Mock.esp_derive_local_mac_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.esp_derive_local_mac_CallbackFunctionPointer(local_mac, universal_mac, Mock.esp_derive_local_mac_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_local_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_derive_local_mac,CMockString_local_mac);
    if (cmock_call_instance->Expected_local_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(local_mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_local_mac, local_mac, cmock_call_instance->Expected_local_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_universal_mac)
  {
    UNITY_SET_DETAILS(CMockString_esp_derive_local_mac,CMockString_universal_mac);
    if (cmock_call_instance->Expected_universal_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(universal_mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_universal_mac, universal_mac, cmock_call_instance->Expected_universal_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.esp_derive_local_mac_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.esp_derive_local_mac_CallbackFunctionPointer(local_mac, universal_mac, Mock.esp_derive_local_mac_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_local_mac_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(local_mac, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)local_mac, (void*)cmock_call_instance->ReturnThruPtr_local_mac_Val,
      cmock_call_instance->ReturnThruPtr_local_mac_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_derive_local_mac(CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance, uint8_t* local_mac, int local_mac_Depth, const uint8_t* universal_mac, int universal_mac_Depth);
void CMockExpectParameters_esp_derive_local_mac(CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance, uint8_t* local_mac, int local_mac_Depth, const uint8_t* universal_mac, int universal_mac_Depth)
{
  cmock_call_instance->Expected_local_mac = local_mac;
  cmock_call_instance->Expected_local_mac_Depth = local_mac_Depth;
  cmock_call_instance->IgnoreArg_local_mac = 0;
  cmock_call_instance->ReturnThruPtr_local_mac_Used = 0;
  cmock_call_instance->Expected_universal_mac = universal_mac;
  cmock_call_instance->Expected_universal_mac_Depth = universal_mac_Depth;
  cmock_call_instance->IgnoreArg_universal_mac = 0;
}

void esp_derive_local_mac_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_derive_local_mac_CALL_INSTANCE));
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_derive_local_mac_CallInstance = CMock_Guts_MemChain(Mock.esp_derive_local_mac_CallInstance, cmock_guts_index);
  Mock.esp_derive_local_mac_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.esp_derive_local_mac_IgnoreBool = (char)1;
}

void esp_derive_local_mac_CMockStopIgnore(void)
{
  if(Mock.esp_derive_local_mac_IgnoreBool)
    Mock.esp_derive_local_mac_CallInstance = CMock_Guts_MemNext(Mock.esp_derive_local_mac_CallInstance);
  Mock.esp_derive_local_mac_IgnoreBool = (char)0;
}

void esp_derive_local_mac_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* local_mac, const uint8_t* universal_mac, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_derive_local_mac_CALL_INSTANCE));
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_derive_local_mac_CallInstance = CMock_Guts_MemChain(Mock.esp_derive_local_mac_CallInstance, cmock_guts_index);
  Mock.esp_derive_local_mac_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_derive_local_mac(cmock_call_instance, local_mac, 1, universal_mac, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_derive_local_mac_AddCallback(CMOCK_esp_derive_local_mac_CALLBACK Callback)
{
  Mock.esp_derive_local_mac_IgnoreBool = (char)0;
  Mock.esp_derive_local_mac_CallbackBool = (char)1;
  Mock.esp_derive_local_mac_CallbackFunctionPointer = Callback;
}

void esp_derive_local_mac_Stub(CMOCK_esp_derive_local_mac_CALLBACK Callback)
{
  Mock.esp_derive_local_mac_IgnoreBool = (char)0;
  Mock.esp_derive_local_mac_CallbackBool = (char)0;
  Mock.esp_derive_local_mac_CallbackFunctionPointer = Callback;
}

void esp_derive_local_mac_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* local_mac, int local_mac_Depth, const uint8_t* universal_mac, int universal_mac_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_derive_local_mac_CALL_INSTANCE));
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_derive_local_mac_CallInstance = CMock_Guts_MemChain(Mock.esp_derive_local_mac_CallInstance, cmock_guts_index);
  Mock.esp_derive_local_mac_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_esp_derive_local_mac(cmock_call_instance, local_mac, local_mac_Depth, universal_mac, universal_mac_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void esp_derive_local_mac_CMockReturnMemThruPtr_local_mac(UNITY_LINE_TYPE cmock_line, uint8_t* local_mac, size_t cmock_size)
{
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_derive_local_mac_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_local_mac_Used = 1;
  cmock_call_instance->ReturnThruPtr_local_mac_Val = local_mac;
  cmock_call_instance->ReturnThruPtr_local_mac_Size = cmock_size;
}

void esp_derive_local_mac_CMockIgnoreArg_local_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_derive_local_mac_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_local_mac = 1;
}

void esp_derive_local_mac_CMockIgnoreArg_universal_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_esp_derive_local_mac_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_derive_local_mac_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.esp_derive_local_mac_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_universal_mac = 1;
}

