/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_aws_esp_ota_ops.h"

static const char* CMockString_active_part = "active_part";
static const char* CMockString_aws_esp_ota_get_boot_flags = "aws_esp_ota_get_boot_flags";
static const char* CMockString_aws_esp_ota_set_boot_flags = "aws_esp_ota_set_boot_flags";
static const char* CMockString_flags = "flags";

typedef struct _CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint32_t Expected_flags;
  bool Expected_active_part;
  char IgnoreArg_flags;
  char IgnoreArg_active_part;

} CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE;

typedef struct _CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  int CallOrder;
  uint32_t* Expected_flags;
  bool Expected_active_part;
  int Expected_flags_Depth;
  char ReturnThruPtr_flags_Used;
  uint32_t* ReturnThruPtr_flags_Val;
  size_t ReturnThruPtr_flags_Size;
  char IgnoreArg_flags;
  char IgnoreArg_active_part;

} CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE;

static struct mock_aws_esp_ota_opsInstance
{
  char aws_esp_ota_set_boot_flags_IgnoreBool;
  esp_err_t aws_esp_ota_set_boot_flags_FinalReturn;
  char aws_esp_ota_set_boot_flags_CallbackBool;
  CMOCK_aws_esp_ota_set_boot_flags_CALLBACK aws_esp_ota_set_boot_flags_CallbackFunctionPointer;
  int aws_esp_ota_set_boot_flags_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE aws_esp_ota_set_boot_flags_CallInstance;
  char aws_esp_ota_get_boot_flags_IgnoreBool;
  esp_err_t aws_esp_ota_get_boot_flags_FinalReturn;
  char aws_esp_ota_get_boot_flags_CallbackBool;
  CMOCK_aws_esp_ota_get_boot_flags_CALLBACK aws_esp_ota_get_boot_flags_CallbackFunctionPointer;
  int aws_esp_ota_get_boot_flags_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE aws_esp_ota_get_boot_flags_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_aws_esp_ota_ops_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.aws_esp_ota_set_boot_flags_CallInstance;
  if (Mock.aws_esp_ota_set_boot_flags_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_aws_esp_ota_set_boot_flags);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.aws_esp_ota_get_boot_flags_CallInstance;
  if (Mock.aws_esp_ota_get_boot_flags_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_aws_esp_ota_get_boot_flags);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_aws_esp_ota_ops_Init(void)
{
  mock_aws_esp_ota_ops_Destroy();
}

void mock_aws_esp_ota_ops_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

esp_err_t aws_esp_ota_set_boot_flags(uint32_t flags, bool active_part)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_aws_esp_ota_set_boot_flags);
  cmock_call_instance = (CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.aws_esp_ota_set_boot_flags_CallInstance);
  Mock.aws_esp_ota_set_boot_flags_CallInstance = CMock_Guts_MemNext(Mock.aws_esp_ota_set_boot_flags_CallInstance);
  if (Mock.aws_esp_ota_set_boot_flags_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.aws_esp_ota_set_boot_flags_FinalReturn;
    memcpy((void*)(&Mock.aws_esp_ota_set_boot_flags_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.aws_esp_ota_set_boot_flags_CallbackBool &&
      Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer(flags, active_part, Mock.aws_esp_ota_set_boot_flags_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_flags)
  {
    UNITY_SET_DETAILS(CMockString_aws_esp_ota_set_boot_flags,CMockString_flags);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_flags, flags, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_active_part)
  {
    UNITY_SET_DETAILS(CMockString_aws_esp_ota_set_boot_flags,CMockString_active_part);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_active_part, active_part, cmock_line, CMockStringMismatch);
  }
  if (Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer(flags, active_part, Mock.aws_esp_ota_set_boot_flags_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_aws_esp_ota_set_boot_flags(CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance, uint32_t flags, bool active_part);
void CMockExpectParameters_aws_esp_ota_set_boot_flags(CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance, uint32_t flags, bool active_part)
{
  cmock_call_instance->Expected_flags = flags;
  cmock_call_instance->IgnoreArg_flags = 0;
  cmock_call_instance->Expected_active_part = active_part;
  cmock_call_instance->IgnoreArg_active_part = 0;
}

void aws_esp_ota_set_boot_flags_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE));
  CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aws_esp_ota_set_boot_flags_CallInstance = CMock_Guts_MemChain(Mock.aws_esp_ota_set_boot_flags_CallInstance, cmock_guts_index);
  Mock.aws_esp_ota_set_boot_flags_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.aws_esp_ota_set_boot_flags_IgnoreBool = (char)1;
}

void aws_esp_ota_set_boot_flags_CMockStopIgnore(void)
{
  if(Mock.aws_esp_ota_set_boot_flags_IgnoreBool)
    Mock.aws_esp_ota_set_boot_flags_CallInstance = CMock_Guts_MemNext(Mock.aws_esp_ota_set_boot_flags_CallInstance);
  Mock.aws_esp_ota_set_boot_flags_IgnoreBool = (char)0;
}

void aws_esp_ota_set_boot_flags_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t flags, bool active_part, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE));
  CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aws_esp_ota_set_boot_flags_CallInstance = CMock_Guts_MemChain(Mock.aws_esp_ota_set_boot_flags_CallInstance, cmock_guts_index);
  Mock.aws_esp_ota_set_boot_flags_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_aws_esp_ota_set_boot_flags(cmock_call_instance, flags, active_part);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void aws_esp_ota_set_boot_flags_AddCallback(CMOCK_aws_esp_ota_set_boot_flags_CALLBACK Callback)
{
  Mock.aws_esp_ota_set_boot_flags_IgnoreBool = (char)0;
  Mock.aws_esp_ota_set_boot_flags_CallbackBool = (char)1;
  Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer = Callback;
}

void aws_esp_ota_set_boot_flags_Stub(CMOCK_aws_esp_ota_set_boot_flags_CALLBACK Callback)
{
  Mock.aws_esp_ota_set_boot_flags_IgnoreBool = (char)0;
  Mock.aws_esp_ota_set_boot_flags_CallbackBool = (char)0;
  Mock.aws_esp_ota_set_boot_flags_CallbackFunctionPointer = Callback;
}

void aws_esp_ota_set_boot_flags_CMockIgnoreArg_flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.aws_esp_ota_set_boot_flags_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_flags = 1;
}

void aws_esp_ota_set_boot_flags_CMockIgnoreArg_active_part(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_set_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.aws_esp_ota_set_boot_flags_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_active_part = 1;
}

esp_err_t aws_esp_ota_get_boot_flags(uint32_t* flags, bool active_part)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_aws_esp_ota_get_boot_flags);
  cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.aws_esp_ota_get_boot_flags_CallInstance);
  Mock.aws_esp_ota_get_boot_flags_CallInstance = CMock_Guts_MemNext(Mock.aws_esp_ota_get_boot_flags_CallInstance);
  if (Mock.aws_esp_ota_get_boot_flags_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.aws_esp_ota_get_boot_flags_FinalReturn;
    memcpy((void*)(&Mock.aws_esp_ota_get_boot_flags_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.aws_esp_ota_get_boot_flags_CallbackBool &&
      Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer(flags, active_part, Mock.aws_esp_ota_get_boot_flags_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_flags)
  {
    UNITY_SET_DETAILS(CMockString_aws_esp_ota_get_boot_flags,CMockString_flags);
    if (cmock_call_instance->Expected_flags == NULL)
      { UNITY_TEST_ASSERT_NULL(flags, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_flags, flags, cmock_call_instance->Expected_flags_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_active_part)
  {
    UNITY_SET_DETAILS(CMockString_aws_esp_ota_get_boot_flags,CMockString_active_part);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_active_part, active_part, cmock_line, CMockStringMismatch);
  }
  if (Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer(flags, active_part, Mock.aws_esp_ota_get_boot_flags_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_flags_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(flags, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)flags, (void*)cmock_call_instance->ReturnThruPtr_flags_Val,
      cmock_call_instance->ReturnThruPtr_flags_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_aws_esp_ota_get_boot_flags(CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance, uint32_t* flags, int flags_Depth, bool active_part);
void CMockExpectParameters_aws_esp_ota_get_boot_flags(CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance, uint32_t* flags, int flags_Depth, bool active_part)
{
  cmock_call_instance->Expected_flags = flags;
  cmock_call_instance->Expected_flags_Depth = flags_Depth;
  cmock_call_instance->IgnoreArg_flags = 0;
  cmock_call_instance->ReturnThruPtr_flags_Used = 0;
  cmock_call_instance->Expected_active_part = active_part;
  cmock_call_instance->IgnoreArg_active_part = 0;
}

void aws_esp_ota_get_boot_flags_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE));
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aws_esp_ota_get_boot_flags_CallInstance = CMock_Guts_MemChain(Mock.aws_esp_ota_get_boot_flags_CallInstance, cmock_guts_index);
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)1;
}

void aws_esp_ota_get_boot_flags_CMockStopIgnore(void)
{
  if(Mock.aws_esp_ota_get_boot_flags_IgnoreBool)
    Mock.aws_esp_ota_get_boot_flags_CallInstance = CMock_Guts_MemNext(Mock.aws_esp_ota_get_boot_flags_CallInstance);
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)0;
}

void aws_esp_ota_get_boot_flags_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* flags, bool active_part, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE));
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aws_esp_ota_get_boot_flags_CallInstance = CMock_Guts_MemChain(Mock.aws_esp_ota_get_boot_flags_CallInstance, cmock_guts_index);
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_aws_esp_ota_get_boot_flags(cmock_call_instance, flags, 1, active_part);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void aws_esp_ota_get_boot_flags_AddCallback(CMOCK_aws_esp_ota_get_boot_flags_CALLBACK Callback)
{
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)0;
  Mock.aws_esp_ota_get_boot_flags_CallbackBool = (char)1;
  Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer = Callback;
}

void aws_esp_ota_get_boot_flags_Stub(CMOCK_aws_esp_ota_get_boot_flags_CALLBACK Callback)
{
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)0;
  Mock.aws_esp_ota_get_boot_flags_CallbackBool = (char)0;
  Mock.aws_esp_ota_get_boot_flags_CallbackFunctionPointer = Callback;
}

void aws_esp_ota_get_boot_flags_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* flags, int flags_Depth, bool active_part, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE));
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.aws_esp_ota_get_boot_flags_CallInstance = CMock_Guts_MemChain(Mock.aws_esp_ota_get_boot_flags_CallInstance, cmock_guts_index);
  Mock.aws_esp_ota_get_boot_flags_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_aws_esp_ota_get_boot_flags(cmock_call_instance, flags, flags_Depth, active_part);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void aws_esp_ota_get_boot_flags_CMockReturnMemThruPtr_flags(UNITY_LINE_TYPE cmock_line, uint32_t* flags, size_t cmock_size)
{
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.aws_esp_ota_get_boot_flags_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_flags_Used = 1;
  cmock_call_instance->ReturnThruPtr_flags_Val = flags;
  cmock_call_instance->ReturnThruPtr_flags_Size = cmock_size;
}

void aws_esp_ota_get_boot_flags_CMockIgnoreArg_flags(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.aws_esp_ota_get_boot_flags_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_flags = 1;
}

void aws_esp_ota_get_boot_flags_CMockIgnoreArg_active_part(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE* cmock_call_instance = (CMOCK_aws_esp_ota_get_boot_flags_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.aws_esp_ota_get_boot_flags_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_active_part = 1;
}

