#ifdef __cplusplus
extern "C" {
#endif

/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_NIMBLE_PORT_FREERTOS_H
#define _MOCK_NIMBLE_PORT_FREERTOS_H

#include "unity.h"
#include "nimble_port_freertos.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_nimble_port_freertos_Init(void);
void mock_nimble_port_freertos_Destroy(void);
void mock_nimble_port_freertos_Verify(void);




#define nimble_port_freertos_init_Ignore() nimble_port_freertos_init_CMockIgnore()
void nimble_port_freertos_init_CMockIgnore(void);
#define nimble_port_freertos_init_StopIgnore() nimble_port_freertos_init_CMockStopIgnore()
void nimble_port_freertos_init_CMockStopIgnore(void);
#define nimble_port_freertos_init_Expect(host_task_fn) nimble_port_freertos_init_CMockExpect(__LINE__, host_task_fn)
void nimble_port_freertos_init_CMockExpect(UNITY_LINE_TYPE cmock_line, TaskFunction_t host_task_fn);
typedef void (* CMOCK_nimble_port_freertos_init_CALLBACK)(TaskFunction_t host_task_fn, int cmock_num_calls);
void nimble_port_freertos_init_AddCallback(CMOCK_nimble_port_freertos_init_CALLBACK Callback);
void nimble_port_freertos_init_Stub(CMOCK_nimble_port_freertos_init_CALLBACK Callback);
#define nimble_port_freertos_init_StubWithCallback nimble_port_freertos_init_Stub
#define nimble_port_freertos_init_IgnoreArg_host_task_fn() nimble_port_freertos_init_CMockIgnoreArg_host_task_fn(__LINE__)
void nimble_port_freertos_init_CMockIgnoreArg_host_task_fn(UNITY_LINE_TYPE cmock_line);
#define nimble_port_freertos_deinit_Ignore() nimble_port_freertos_deinit_CMockIgnore()
void nimble_port_freertos_deinit_CMockIgnore(void);
#define nimble_port_freertos_deinit_StopIgnore() nimble_port_freertos_deinit_CMockStopIgnore()
void nimble_port_freertos_deinit_CMockStopIgnore(void);
#define nimble_port_freertos_deinit_Expect() nimble_port_freertos_deinit_CMockExpect(__LINE__)
void nimble_port_freertos_deinit_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_nimble_port_freertos_deinit_CALLBACK)(int cmock_num_calls);
void nimble_port_freertos_deinit_AddCallback(CMOCK_nimble_port_freertos_deinit_CALLBACK Callback);
void nimble_port_freertos_deinit_Stub(CMOCK_nimble_port_freertos_deinit_CALLBACK Callback);
#define nimble_port_freertos_deinit_StubWithCallback nimble_port_freertos_deinit_Stub

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif


#ifdef __cplusplus
}
#endif
