/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_nimble_port_freertos.h"

static const char* CMockString_host_task_fn = "host_task_fn";
static const char* CMockString_nimble_port_freertos_deinit = "nimble_port_freertos_deinit";
static const char* CMockString_nimble_port_freertos_init = "nimble_port_freertos_init";

typedef struct _CMOCK_nimble_port_freertos_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  TaskFunction_t Expected_host_task_fn;
  char IgnoreArg_host_task_fn;

} CMOCK_nimble_port_freertos_init_CALL_INSTANCE;

typedef struct _CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;

} CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE;

static struct mock_nimble_port_freertosInstance
{
  char nimble_port_freertos_init_IgnoreBool;
  char nimble_port_freertos_init_CallbackBool;
  CMOCK_nimble_port_freertos_init_CALLBACK nimble_port_freertos_init_CallbackFunctionPointer;
  int nimble_port_freertos_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nimble_port_freertos_init_CallInstance;
  char nimble_port_freertos_deinit_IgnoreBool;
  char nimble_port_freertos_deinit_CallbackBool;
  CMOCK_nimble_port_freertos_deinit_CALLBACK nimble_port_freertos_deinit_CallbackFunctionPointer;
  int nimble_port_freertos_deinit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE nimble_port_freertos_deinit_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_nimble_port_freertos_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.nimble_port_freertos_init_CallInstance;
  if (Mock.nimble_port_freertos_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nimble_port_freertos_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nimble_port_freertos_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.nimble_port_freertos_deinit_CallInstance;
  if (Mock.nimble_port_freertos_deinit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_nimble_port_freertos_deinit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.nimble_port_freertos_deinit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_nimble_port_freertos_Init(void)
{
  mock_nimble_port_freertos_Destroy();
}

void mock_nimble_port_freertos_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void nimble_port_freertos_init(TaskFunction_t host_task_fn)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nimble_port_freertos_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nimble_port_freertos_init);
  cmock_call_instance = (CMOCK_nimble_port_freertos_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nimble_port_freertos_init_CallInstance);
  Mock.nimble_port_freertos_init_CallInstance = CMock_Guts_MemNext(Mock.nimble_port_freertos_init_CallInstance);
  if (Mock.nimble_port_freertos_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.nimble_port_freertos_init_CallbackBool &&
      Mock.nimble_port_freertos_init_CallbackFunctionPointer != NULL)
  {
    Mock.nimble_port_freertos_init_CallbackFunctionPointer(host_task_fn, Mock.nimble_port_freertos_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->IgnoreArg_host_task_fn)
  {
    UNITY_SET_DETAILS(CMockString_nimble_port_freertos_init,CMockString_host_task_fn);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_host_task_fn), (void*)(&host_task_fn), sizeof(TaskFunction_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.nimble_port_freertos_init_CallbackFunctionPointer != NULL)
  {
    Mock.nimble_port_freertos_init_CallbackFunctionPointer(host_task_fn, Mock.nimble_port_freertos_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_nimble_port_freertos_init(CMOCK_nimble_port_freertos_init_CALL_INSTANCE* cmock_call_instance, TaskFunction_t host_task_fn);
void CMockExpectParameters_nimble_port_freertos_init(CMOCK_nimble_port_freertos_init_CALL_INSTANCE* cmock_call_instance, TaskFunction_t host_task_fn)
{
  memcpy((void*)(&cmock_call_instance->Expected_host_task_fn), (void*)(&host_task_fn),
         sizeof(TaskFunction_t[sizeof(host_task_fn) == sizeof(TaskFunction_t) ? 1 : -1])); /* add TaskFunction_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_host_task_fn = 0;
}

void nimble_port_freertos_init_CMockIgnore(void)
{
  Mock.nimble_port_freertos_init_IgnoreBool = (char)1;
}

void nimble_port_freertos_init_CMockStopIgnore(void)
{
  Mock.nimble_port_freertos_init_IgnoreBool = (char)0;
}

void nimble_port_freertos_init_CMockExpect(UNITY_LINE_TYPE cmock_line, TaskFunction_t host_task_fn)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nimble_port_freertos_init_CALL_INSTANCE));
  CMOCK_nimble_port_freertos_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nimble_port_freertos_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nimble_port_freertos_init_CallInstance = CMock_Guts_MemChain(Mock.nimble_port_freertos_init_CallInstance, cmock_guts_index);
  Mock.nimble_port_freertos_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_nimble_port_freertos_init(cmock_call_instance, host_task_fn);
}

void nimble_port_freertos_init_AddCallback(CMOCK_nimble_port_freertos_init_CALLBACK Callback)
{
  Mock.nimble_port_freertos_init_IgnoreBool = (char)0;
  Mock.nimble_port_freertos_init_CallbackBool = (char)1;
  Mock.nimble_port_freertos_init_CallbackFunctionPointer = Callback;
}

void nimble_port_freertos_init_Stub(CMOCK_nimble_port_freertos_init_CALLBACK Callback)
{
  Mock.nimble_port_freertos_init_IgnoreBool = (char)0;
  Mock.nimble_port_freertos_init_CallbackBool = (char)0;
  Mock.nimble_port_freertos_init_CallbackFunctionPointer = Callback;
}

void nimble_port_freertos_init_CMockIgnoreArg_host_task_fn(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_nimble_port_freertos_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_nimble_port_freertos_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.nimble_port_freertos_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_host_task_fn = 1;
}

void nimble_port_freertos_deinit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_nimble_port_freertos_deinit);
  cmock_call_instance = (CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.nimble_port_freertos_deinit_CallInstance);
  Mock.nimble_port_freertos_deinit_CallInstance = CMock_Guts_MemNext(Mock.nimble_port_freertos_deinit_CallInstance);
  if (Mock.nimble_port_freertos_deinit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.nimble_port_freertos_deinit_CallbackBool &&
      Mock.nimble_port_freertos_deinit_CallbackFunctionPointer != NULL)
  {
    Mock.nimble_port_freertos_deinit_CallbackFunctionPointer(Mock.nimble_port_freertos_deinit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.nimble_port_freertos_deinit_CallbackFunctionPointer != NULL)
  {
    Mock.nimble_port_freertos_deinit_CallbackFunctionPointer(Mock.nimble_port_freertos_deinit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void nimble_port_freertos_deinit_CMockIgnore(void)
{
  Mock.nimble_port_freertos_deinit_IgnoreBool = (char)1;
}

void nimble_port_freertos_deinit_CMockStopIgnore(void)
{
  Mock.nimble_port_freertos_deinit_IgnoreBool = (char)0;
}

void nimble_port_freertos_deinit_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE));
  CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE* cmock_call_instance = (CMOCK_nimble_port_freertos_deinit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.nimble_port_freertos_deinit_CallInstance = CMock_Guts_MemChain(Mock.nimble_port_freertos_deinit_CallInstance, cmock_guts_index);
  Mock.nimble_port_freertos_deinit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
}

void nimble_port_freertos_deinit_AddCallback(CMOCK_nimble_port_freertos_deinit_CALLBACK Callback)
{
  Mock.nimble_port_freertos_deinit_IgnoreBool = (char)0;
  Mock.nimble_port_freertos_deinit_CallbackBool = (char)1;
  Mock.nimble_port_freertos_deinit_CallbackFunctionPointer = Callback;
}

void nimble_port_freertos_deinit_Stub(CMOCK_nimble_port_freertos_deinit_CALLBACK Callback)
{
  Mock.nimble_port_freertos_deinit_IgnoreBool = (char)0;
  Mock.nimble_port_freertos_deinit_CallbackBool = (char)0;
  Mock.nimble_port_freertos_deinit_CallbackFunctionPointer = Callback;
}

