#ifndef DEFAULT_CERTS_H
#define DEFAULT_CERTS_H

#define CLOUD_DEVICE_PROVISIONING_ADDRESS "mqtts://global.azure-devices-provisioning.net"
#define DEVICE_PROVISIONING_ID_SCOPE      "0ne00B73235"

#define DEFAULT_SERVER_PUBLIC_CERT \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBh\n" \
    "MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n" \
    "d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH\n" \
    "MjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVT\n" \
    "MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\n" \
    "b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG\n" \
    "9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI\n" \
    "2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx\n" \
    "1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQ\n" \
    "q2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5Wz\n" \
    "tCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQ\n" \
    "vIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAP\n" \
    "BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV\n" \
    "5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY\n" \
    "1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4\n" \
    "NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NG\n" \
    "Fdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ91\n" \
    "8rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTe\n" \
    "pLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTfl\n" \
    "MrY=\n" \
    "-----END CERTIFICATE-----\n"

// example HTTP Server Public Key, replace with the one for your HTTP Server
#define DEFAULT_HTTP_SERVER_PUBLIC_KEY \
    "-----BEGIN CERTIFICATE-----\n" \
    "MIIDkzCCAnugAwIBAgIUVDqCmVldG9pJWyndbtqqtsSwmLUwDQYJKoZIhvcNAQEL\n" \
    "BQAwWTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM\n" \
    "GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDESMBAGA1UEAwwJMTAuNDIuMC4xMB4X\n" \
    "DTIzMTIxMjExNDQzOVoXDTMzMTIwOTExNDQzOVowWTELMAkGA1UEBhMCQVUxEzAR\n" \
    "BgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5\n" \
    "IEx0ZDESMBAGA1UEAwwJMTAuNDIuMC4xMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\n" \
    "MIIBCgKCAQEAyFbMpiQ6/GqbXFvmNiPZW6RajVIRCSOInqGq2QbH82SwYSH1kBbK\n" \
    "RDOUXmn3VmBEY0UsGVQ79q1PpCRURpilmFzF+BElSdYa9vMvez84W2PPed7Jsv6S\n" \
    "mPmp9VB3cEogbUQWUv2wHOsoDePbXITyi/iAJHALjTZ06woQM+4s/emKONIdv1ea\n" \
    "aAJukvxKfRaHv21ZW0pRsa/azV9wNpvjm68xgRksTHM3fumGBwVP75FO8+e60Bf3\n" \
    "t606gSBlKRrKqYgSTz2ftvSH5G6O+PIiyTXNVPEiUhPOH4sAGpGsmqxmX1Ls5qOO\n" \
    "4/2fSF5k/TICg/yDqgtYgv4dOYz2wTrD5wIDAQABo1MwUTAdBgNVHQ4EFgQUnnTT\n" \
    "r61XTFE7PIgxySH9i/dWM8wwHwYDVR0jBBgwFoAUnnTTr61XTFE7PIgxySH9i/dW\n" \
    "M8wwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAfpvBG9jj13su\n" \
    "A7rPFwyoGqifGKME52CUG0+noTA6CbM9cFfUFet/ty7ACxdcInSIaUfrfbgcj0yk\n" \
    "iRSK5yuATgCdsAaGOWfr44trvEIoGiaceeSo5qVywq2MmVmSFmaffwOupLxit7SY\n" \
    "cKHWhWJaWk78gfBdLmCjgf5flED6BO6ahc2gLltgPfnObbeXOanm8RONuhEdpN8n\n" \
    "h6vRWu2nq/FKQwHFDjwf6tBE2YMVdJ8JCyO9gwbfdpOSZ4JLmrFWIjJsDeRJnFmV\n" \
    "sBPZAFNmUN5VCDRjob3GdhN++wignpkk3MAFvQZOf4BmOuoE3+73JUMPVhg6HBdA\n" \
    "GQ+9Pgsfyg==\n" \
    "-----END CERTIFICATE-----\n"
#endif // DEFAULT_CERTS_H